- type: job
  id: ArbeiterATH
  name: job-name-arbeiter
  description: job-description-arbeiter
  playTimeTracker: JobArbeiterATH
  weight: 1
  startingGear: ArbeiterGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconArbeiter"
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Reptilian
        - Oni
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: ATH 
      - type: LanguageAdder
        addSpoken:
          - SolBasic
          - Tradeband
        addUnderstood:
          - SolBasic
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority

- type: startingGear
  id: ArbeiterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthorityArbeiter
    shoes: ClothingShoesBootsJack
    id: ArbeiterPDA
    ears: ClothingHeadsetAuthority
