- type: job
  id: ChirurgeonATH
  name: job-name-chirurgeon
  description: job-description-chirurgeon
  playTimeTracker: JobChirurgeonATH
  weight: 97
  startingGear: ChirurgeonGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconChirurgeon"
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Oni
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-smarts
      - type: HullrotFaction
        faction: ATH
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 2.5
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority
  - Authoritymed

- type: startingGear
  id: ChirurgeonGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthorityChirurgeon
    outerClothing: ClothingOuterCoatAuthorityChirurgeon
    shoes: ClothingShoesBootsJack
    id: ChirurgeonPDA
    ears: ClothingHeadsetAuthority
