- type: job
  id: StewardATH
  name: job-name-steward
  description: job-description-steward
  playTimeTracker: ConscriptDSM
  weight: 99
  startingGear: StewardGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconSteward"
  supervisors: job-supervisors-ath
  requirements:
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-steward
      - type: HullrotFaction
        faction: ATH
      - type: LanguageAdder
        addSpoken:
          - SolBasic
          - Tradeband
        addUnderstood:
          - SolBasic
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority
  - AuthorityRanking
  - Authoritymed
  - AuthoritySupply

- type: startingGear
  id: StewardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthoritySteward
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatAuthoritySteward
    neck: ClothingNeckAuthorityStewardCape
    id: StewardPDA
    ears: ClothingHeadsetAuthority
