- type: job
  id: ForscherATH
  name: job-name-forscher
  description: job-description-forscher
  playTimeTracker: JobForscherATH
  weight: 98
  startingGear: ForscherGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconForscher"
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Oni
    - !type:FactionRequirement
      factionID: "ATH"
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-smarts
      - type: HullrotFaction
        faction: ATH
      - type: LanguageAdder
        addSpoken:
          - SolBasic
        addUnderstood:
          - SolBasic
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority
  - Authoritymed

- type: startingGear
  id: ForscherGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthorityForscher
    outerClothing: ClothingOuterCoatAuthorityForscher
    shoes: ClothingShoesBootsJack
    id: ForscherPDA
    ears: ClothingHeadsetAuthority
