- type: job
  id: HandelsATH
  name: job-name-handels
  description: job-description-handels
  playTimeTracker: JobHandelsATH
  weight: 96
  startingGear: HandelsGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconHandels"
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Reptilian
        - Oni
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: ATH
      - type: LanguageAdder
        addSpoken:
          - SolBasic
          - Tradeband
        addUnderstood:
          - SolBasic
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority
  - AuthoritySupply

- type: startingGear
  id: HandelsGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthorityHandels
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterCoatAuthorityHandels
    id: HandelsPDA
    ears: ClothingHeadsetAuthority
