- type: job
  id: KanoneerATH
  name: job-name-kanoneer
  description: job-description-kanoneer
  playTimeTracker: JobKanoneerATH
  weight: 2
  startingGear: KanoneerGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconKanoneer"
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Reptilian
        - Oni
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-kanoneer
      - type: HullrotFaction
        faction: ATH
      - type: LanguageAdder
        addSpoken:
          - SolBasic
        addUnderstood:
          - SolBasic
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority

- type: startingGear
  id: KanoneerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthorityKanoneer
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatAuthorityKanoneer
    gloves: ClothingHandsGlovesFingerless
    id: KanoneerPDA
    ears: ClothingHeadsetAuthority
