- type: job
  id: KommandantATH
  name: job-name-kommandant
  description: job-description-kommandant
  playTimeTracker: JobKommandantATH
  weight: 100
  startingGear: KommandantGear
  alwaysUseSpawner: true
  icon: "JobIconKommandant"
  requireAdminNotify: true
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-kommandant
      - type: HullrotFaction
        faction: ATH
      - type: LanguageAdder
        addSpoken:
          - SolBasic
          - Tradeband
        addUnderstood:
          - SolBasic
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Kommandant
  - Authority
  - AuthorityRanking
  - Authoritymed
  - AuthoritySupply

- type: startingGear
  id: KommandantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthorityKommandant
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatAuthorityKommandant
    outerClothing: ClothingOuterCoatAuthorityKommandant
    id: KommandantPDA
    ears: ClothingHeadsetAuthority
