- type: job
  id: LeutnantATH
  name: job-name-leutnant
  description: job-description-leutnant
  playTimeTracker: JobLeutnantATH
  weight: 50
  startingGear: LeutnantGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconLeutnant"
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Reptilian
        - Oni
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-leutnant
      - type: HullrotFaction
        faction: ATH
      - type: LanguageAdder
        addSpoken:
          - SolBasic
        addUnderstood:
          - SolBasic
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority
  - AuthorityRanking

- type: startingGear
  id: LeutnantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthorityLeutnant
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatAuthorityLeutnant
    outerClothing: ClothingOuterCoatAuthorityLeutnant
    id: LeutnantPDA
    ears: ClothingHeadsetAuthority
