- type: job
  id: LogistatATH
  name: job-name-logistat
  description: job-description-logistat
  playTimeTracker: JobLogistatATH
  weight: 95
  startingGear: LogistatGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconLogistat"
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 2500
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-logistat
      - type: HullrotFaction
        faction: ATH
      - type: LanguageAdder
        addSpoken:
          - SolBasic
          - Tradeband
        addUnderstood:
          - SolBasic
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority
  - AuthorityRanking
  - AuthoritySupply

- type: startingGear
  id: LogistatGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthorityLogistitat
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatAuthorityLogistitat
    neck: ClothingNeckAuthorityLogistatCape
    id: LogistatPDA
    ears: ClothingHeadsetAuthority
