- type: job
  id: OberartzATH
  name: job-name-oberartz
  description: job-description-oberartz
  playTimeTracker: JobOberartzATH
  weight: 94
  startingGear: OberartzGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconOberartz"
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 36000
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-smarts
      - type: HullrotFaction
        faction: ATH
      - type: LanguageAdder
        addSpoken:
          - SolBasic
          - Tradeband
        addUnderstood:
          - SolBasic
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority
  - AuthorityRanking
  - Authoritymed

- type: startingGear
  id: OberartzGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthorityOberartz
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterCoatAuthorityOberartz
    id: OberartzPDA
    ears: ClothingHeadsetAuthority
