- type: job
  id: SanitatATH
  name: job-name-sanitatATH
  description: job-description-sanitat
  playTimeTracker: JobSanitatATH
  weight: 3
  startingGear: SanitatGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconSanitat"
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Reptilian
        - Oni
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-sanitat
      - type: HullrotFaction
        faction: ATH
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 1.75
      - type: LanguageAdder
        addSpoken:
          - SolBasic
        addUnderstood:
          - SolBasic
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority
  - Authoritymed

- type: startingGear
  id: SanitatGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthoritySanitat
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatAuthoritySanitat
    gloves: ClothingHandsGlovesFingerless
    id: SanitatPDA
    ears: ClothingHeadsetAuthority
