- type: job
  id: SoldatATH
  name: job-name-soldat
  description: job-description-soldat
  playTimeTracker: JobSoldatATH
  weight: 4
  startingGear: SoldatGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconSoldat"
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Reptilian
        - Oni
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-soldatATH
      - type: HullrotFaction
        faction: ATH
      - type: LanguageAdder
        addSpoken:
          - SolBasic
        addUnderstood:
          - SolBasic
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority

- type: startingGear
  id: SoldatGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthoritySoldat
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatAuthoritySoldat
    gloves: ClothingHandsGlovesFingerless
    id: SoldatPDA
    ears: ClothingHeadsetAuthority
