- type: job
  id: VorarbeiterATH
  name: job-name-vorarbeiter
  description: job-description-vorarbeiter
  playTimeTracker: JobVorarbeiterATH
  weight: 93
  startingGear: VorarbeiterGear
  alwaysUseSpawner: true
  icon: "JobIconVorarbeiter"
  requireAdminNotify: true
  supervisors: job-supervisors-ath
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "ATH"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Reptilian
        - Oni
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: ATH
      - type: LanguageAdder
        addSpoken:
          - SolBasic
          - Tradeband
        addUnderstood:
          - SolBasic
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority
  - AuthoritySupply

- type: startingGear
  id: VorarbeiterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthorityVorarbeiter
    outerClothing: ClothingOuterCoatAuthorityVorarbeiter
    shoes: ClothingShoesBootsJack
    id: VorarbeiterPDA
    ears: ClothingHeadsetAuthority
