- type: job
  id: AcolyteTAP
  name: job-name-acolytetap
  description: job-description-acolytetap
  playTimeTracker: JobAcolyteTAP
  weight: 5
  startingGear: AcolyteTAPGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconAcolyteFamilies"
  supervisors: job-supervisors-tap
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "TAP"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Reptilian
        - Moth
        - Arachnid
        - Reptilian
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-acolytetap
      - type: HullrotFaction
        faction: TAP
      - type: Telepathic
      - type: LanguageAdder
        addSpoken:
          - OldTaypani
        addUnderstood:
          - OldTaypani
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - Families
  - Arabet
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - External
  - Captain # Frontier

- type: startingGear
  id: AcolyteTAPGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBodysuit
    back: ClothingBackpackSatchelLeatherFilledNCWL
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterArmorAcolyteRobes
    id: AcolyteTAPPDA
    ears: ClothingHeadsetFamilies
