- type: job
  id: HangarTechTAP
  name: job-name-hangartech
  description: job-description-hangartech
  playTimeTracker:  JobHangarTechTAP
  weight: 1
  startingGear: HangarTechGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconHangarTech"
  supervisors: job-supervisors-tap
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "TAP"
    - !type:CharacterSpeciesRequirement
      species:
        - Moth
        - Arachnid
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-hangartech
      - type: HullrotFaction
        faction: TAP
      - type: Telepathic
      - type: LanguageAdder
        addSpoken:
          - OldTaypani
        addUnderstood:
          - OldTaypani
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - Families
  - Thukker
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - External
  - Captain # Frontier

- type: startingGear
  id: HangarTechGear
  equipment:
    jumpsuit:  ClothingUniformJumpsuitHangarTechnician
    back: ClothingBackpackSatchelFilled
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatBeretQM
    id: HangarTechPDA
    ears: ClothingHeadsetFamilies
    gloves: ClothingHandsGlovesFingerless
