- type: job
  id: ServileTAP
  name: job-name-servile
  description: job-description-servile
  playTimeTracker:  JobServileTAP
  weight: 50
  startingGear: ServileGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconServile"
  supervisors: job-supervisors-tap
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:FactionRequirement
      factionID: "TAP"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Reptilian
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - WheelchairBound
        - Pacifist
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-servile
      - type: HullrotFaction
        faction: TAP
      - type: Telepathic
      - type: LanguageAdder
        addSpoken:
          - OldTaypani
        addUnderstood:
          - OldTaypani
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - AlseikServile
  - Families
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - External
  - Captain # Frontier

- type: startingGear
  id: ServileGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitServile
    back: ClothingBackpackSatchelFilled
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatServile
    id: ServilePDA
    outerClothing: ClothingOuterArmorServileAlseik
    ears: ClothingHeadsetFamilies
    gloves: ClothingHandsGlovesFingerless
