- type: job
  id: AcolyteSRM
  name: job-name-acolyte
  description: job-description-apprenticehunter
  playTimeTracker: JobAcolyteSRM
  weight: 1
  startingGear: AcolyteGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconAcolyte"
  supervisors: job-supervisors-srm-apprentice
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 21600
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:SexRequirement
      sex: Male
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  access:
  - Command
  - Hunter
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: SRM
      - type: BibleUser
      - type: LanguageAdder
        addSpoken:
          - LowImperial
          - Saintspact
        addUnderstood:
          - LowImperial
          - Saintspact
      - type: InnatePsionicPowers
        powersToAdd:
          - TelepathyPower
          - AssayPower

- type: startingGear
  id: AcolyteGear
  equipment:
    id: AcolytePDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunterAcolyte
    shoes: ClothingShoesBootsHunter
    gloves: ClothingHandsGlovesHunter
    pocket2: RomaineBible
    belt: ClothingBeltAssault
