- type: job
  id: HunterSRM
  name: job-name-hunter
  description: job-description-hunter
  playTimeTracker: JobHunterSRM
  weight: 3
  startingGear: HunterGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconHunter"
  supervisors: job-supervisors-srm-hunters
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 43200
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:SexRequirement
      sex: Male
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  access:
  - Command
  - Hunter
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: SRM
      - type: LanguageAdder
        addSpoken:
          - LowImperial
          - Saintspact
        addUnderstood:
          - LowImperial
          - Saintspact
      - type: InnatePsionicPowers
        powersToAdd:
          - TelepathyPower
          - AssayPower

- type: startingGear
  id: HunterGear
  equipment:
    id: HunterPDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunter
    head: ClothingHeadHatHunter
    shoes: ClothingShoesBootsHunter
    gloves: ClothingHandsGlovesHunter
    pocket2: RomaineBible
    belt: ClothingBeltAssault
