- type: job
  id: MontagneSRM
  name: job-name-montagne
  description: job-description-montagne
  playTimeTracker: JobMontagneSRM
  weight: 100
  startingGear: MontagneGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconMontagne"
  supervisors: job-supervisors-srm-leaders
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 64800
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:SexRequirement
      sex: Male
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  access:
  - Command
  - Hunter
  - HunterSenior
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: SRM
      - type: LanguageAdder
        addSpoken:
          - Saintspact
          - HighImperial
          - LowImperial
        addUnderstood:
          - Saintspact
          - HighImperial
          - LowImperial
      - type: InnatePsionicPowers
        powersToAdd:
          - TelepathyPower
          - AssayPower

- type: startingGear
  id: MontagneGear
  equipment:
    id: MontagnePDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunter
    head: ClothingHeadHelmetHunterBasic
    shoes: ClothingShoesBootsHunter
    outerClothing: ClothingOuterArmorHunterDusterMontagne
    gloves: ClothingHandsGlovesHunter
    pocket2: RomaineBible
    belt: ClothingBeltAssault
