- type: job
  id: MontagneSRM
  name: job-name-montagne
  description: job-description-montagne
  playTimeTracker: JobMontagneSRM
  weight: 100
  startingGear: MontagneGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconMontagne"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 40000
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
  access:
  - Command
  - Hunter
  - HunterSenior
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: SRM
      - type: LanguageAdder
        addSpoken:
          - HighImperial
          - LowImperial
          - Tradeband
        addUnderstood:
          - HighImperial
          - LowImperial
          - Tradeband
      - type: InnatePsionicPowers
        powersToAdd:
          - TelepathyPower
          - assayPower

- type: startingGear
  id: MontagneGear
  equipment:
    id: MontagnePDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunter
    head: ClothingHeadHelmetHunterBasic
    shoes: ClothingShoesBootsHunter
    outerClothing: ClothingOuterArmorHunterDusterMontagne
    gloves: ClothingHandsGlovesHunter
