- type: job
  id: OverseerSRM
  name: job-name-overseer
  description: job-description-overseer
  playTimeTracker: JobOverseerSRM
  weight: 99
  startingGear: OverseerGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconOverseer"
  supervisors: job-supervisors-srm-overseer
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterOverallTimeRequirement
      min: 500000
    - !type:SexRequirement
      sex: Male
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  access:
  - Command
  - Hunter
  - HunterSenior
  - HunterOverseer
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: SRM
      - type: LanguageAdder
        addSpoken:
          - Saintspact
          - HighImperial
          - LowImperial
        addUnderstood:
          - Saintspact
          - HighImperial
          - LowImperial
      - type: InnatePsionicPowers
        powersToAdd:
          - TelepathyPower
          - AssayPower

- type: startingGear
  id: OverseerGear
  equipment:
    id: OverseerPDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitOverseer
    head: ClothingHeadHatHunterOverseer
    shoes: ClothingShoesBootsHunter
    outerClothing: ClothingOuterArmorHunterDusterOverseer
    gloves: ClothingHandsGlovesHunter
    pocket2: RomaineBible
    belt: ClothingBeltAssault
