- type: job
  id: TenderSRM
  name: job-name-tender
  description: job-description-tender
  playTimeTracker: JobTenderSRM
  weight: 2
  startingGear: TenderGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconTender"
  supervisors: job-supervisors-srm-hunters
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 57600
    - !type:FactionRequirement
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:SexRequirement
      sex: Male
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  access:
  - Command
  - Hunter
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: SRM
      - type: BibleUser
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 1.75
      - type: LanguageAdder
        addSpoken:
          - LowImperial
          - Saintspact
        addUnderstood:
          - LowImperial
          - Saintspact
      - type: InnatePsionicPowers
        powersToAdd:
          - TelepathyPower
          - AssayPower

- type: startingGear
  id: TenderGear
  equipment:
    id: TenderPDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunterAcolyte
    shoes: ClothingShoesBootsHunter
    head: ClothingHeadHatHunterTender
    outerClothing: ClothingOuterArmorHunterTender
    gloves: ClothingHandsGlovesHunter
    pocket1: RomaineBible
    pocket2: RomaineBible
    belt: ClothingBeltAssault
