
- type: job
  id: MedicalBorg
  name: job-name-medical-borg
  description: job-description-medical-borg
  playTimeTracker: JobMedicalBorg
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 216000 #60 hrs
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 21600 #6 hrs
  canBeAntag: false
  icon: JobIconMedicalBorg
  supervisors: job-supervisors-cmo
  jobEntity: PlayerBorgMedical
