- type: job
  id: ConscriptSubmachinegunDSM
  name: job-name-conscript-dsm-smg
  description: job-description-conscript-dsm-smg #change me later
  playTimeTracker: ConscriptJobSubmachinegunDSM
  weight: 10
  startingGear: ConscriptSubmachinegunDSMGear
  alwaysUseSpawner: true
  icon: "JobIconImperialLevyman"
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-manatarms
  access:
  - Command
  - Maintenance
  - Service
  - DSMGeneral
  - DSMJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - Empire
  - DSMArmory
  - DSMCommand

- type: startingGear
  id: ConscriptSubmachinegunDSMGear
  equipment:
    head: ClothingHeadHelmetImperialTrooperHelmet
    mask: ClothingMaskImperialCombatGasmask
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    outerClothing: ClothingOuterArmorImperialTrooperArmor
    shoes: ClothingShoesBootsImperialJackboots
    belt: ClothingBeltAssaultFilledSubmachinegun
    gloves: ClothingHandsGlovesImperialLonggloves
    back: ClothingBackpackDSM
    pocket1: EmergencyOxygenTankFilled
    pocket2: GrenadeFlashBang
    ears: ClothingHeadsetEmpire
    id: LevymanPDA
    suitstorage: WeaponSubMachineGunDSMArbiter
  inhand:
    - WeaponPistolComplianceImperial
