- type: job
  id: ConscriptShipCrewDSM
  name: job-name-conscript-dsm-ship-crew
  description: job-description-conscript-dsm-ship-crew
  playTimeTracker: ConscriptJobShipCrewDSM
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 55
  startingGear: ConscriptShipCrewDSMGear
  alwaysUseSpawner: true
  icon: "JobIconImperialForeman"
  requireAdminNotify: true
  supervisors: job-supervisors-imperial
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-dsm-crew
      - type: HullrotFaction
        faction: DSM
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - DSMGeneral
  - Service
  - DSMJail
  - DSMArmory
  - DSMCommand
  - External
  - Captain # Frontier
  - Empire

- type: startingGear
  id: ConscriptShipCrewDSMGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryColorBlue
    neck: ClothingNeckIFFCyan
    back: ClothingBackpackDSM
    shoes: ClothingShoesBootsImperialLongboots
    head: ClothingHeadHatBeretNavy
    id: LevymanPDA
    belt: ClothingBeltAssaultFilledCrew
    pocket1: EmergencyOxygenTankFilled
    ears: ClothingHeadsetEmpire
  inhand:
    - WeaponPistolNeoVolker
