- type: job
  id: ConscriptRiflemanDSM
  name: job-name-conscript-dsm-rifleman
  description: job-description-conscript-dsm-rifleman #change me later
  playTimeTracker: ConscriptJobRiflemanDSM
  weight: 10
  startingGear: ConscriptRiflemanDSMGear
  alwaysUseSpawner: true
  icon: "JobIconImperialLevyman"
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-manatarms
      - type: HullrotFaction
        faction: DSM
  access:
  - Command
  - Maintenance
  - Service
  - DSMGeneral
  - DSMJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - Empire
  - DSMArmory
  - DSMCommand

- type: startingGear
  id: ConscriptRiflemanDSMGear
  equipment:
    head: ClothingHeadHelmetImperialTrooperHelmet
    neck: ClothingNeckIFFCyan
    mask: ClothingMaskImperialCombatGasmask
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    outerClothing: ClothingOuterArmorImperialTrooperArmor
    shoes: ClothingShoesBootsImperialJackboots
    belt: ClothingBeltAssaultFilledRifleman
    gloves: ClothingHandsGlovesImperialLonggloves
    back: ClothingBackpackDSM
    pocket1: EmergencyOxygenTankFilled
    pocket2: GrenadeShrapnel
    ears: ClothingHeadsetEmpire
    id: LevymanPDA
    suitstorage: WeaponSniperDSMLegax
  inhand:
    - WeaponPistolComplianceImperial
