- type: job
  id: ConscriptLeaderDSM
  name: job-name-conscript-dsm-leader
  description: job-description-conscript-dsm-leader
  playTimeTracker: ConscriptJobLeaderDSM
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 55
  startingGear: ConscriptLeaderDSMGear
  alwaysUseSpawner: true
  icon: "JobIconImperialAdjutant"
  requireAdminNotify: true
  supervisors: job-supervisors-conscript-dsm-high
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-dsm-leader
      - type: HullrotFaction
        faction: DSM
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - DSMGeneral
  - Service
  - DSMJail
  - DSMArmory
  - DSMCommand
  - External
  - Captain # Frontier
  - Empire

- type: startingGear
  id: ConscriptLeaderDSMGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialGovernor
    neck: ClothingNeckIFFCyan
    back: ClothingBackpackDSM
    shoes: ClothingShoesBootsImperialLongboots
    head: ClothingHeadHatImperialBeret
    outerClothing: ClothingOuterHardsuitImperialCommand
    id: KnightPDA
    belt: ClothingBeltAssaultFilledAdjutant
    pocket1: EmergencyOxygenTankFilled
    ears: ClothingHeadsetEmpire
    suitstorage: WeaponSniperDSMLegax
  inhand:
    - WeaponPistolNeoVolker
