- type: job
  id: ConscriptCadetDSM
  name: job-name-conscript-dsm-cadet
  description: job-description-conscript-dsm-cadet #change me later
  playTimeTracker: ConscriptJobCadetDSM
  weight: 10
  startingGear: ConscriptCadetDSMGear
  alwaysUseSpawner: true
  icon: "JobIconImperialFreeholder"
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-conscript-dsm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-dsm-new
      - type: HullrotFaction
        faction: DSM
  access:
  - Command
  - Maintenance
  - Service
  - DSMGeneral
  - DSMJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - Empire
  - DSMArmory
  - DSMCommand

- type: startingGear
  id: ConscriptCadetDSMGear
  equipment:
    head: ClothingHeadHelmetImperialTrooperHelmet
    neck: ClothingNeckIFFCyan
    mask: ClothingMaskImperialCombatGasmask
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    outerClothing: ClothingOuterArmorImperialTrooperArmor
    shoes: ClothingShoesBootsMagCombat
    belt: ClothingBeltAssaultFilledRifleman
    gloves: ClothingHandsGlovesImperialLonggloves
    back: ClothingBackpackDSM
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: SmokeGrenade
    ears: ClothingHeadsetEmpire
    id: LevymanPDA
    suitstorage: WeaponSniperDSMLegax
    eyes: ClothingEyesHudSecurity
  inhand:
    - WeaponPistolComplianceImperial
  storage:
    back:
      - VoidsuitKitDSM
      - BoxMRE
      - BoxFlare
