- type: job
  id: ConscriptShotgunDSM
  name: job-name-conscript-dsm-shotgun
  description: job-description-conscript-dsm-shotgun #change me later
  playTimeTracker: ConscriptJobShotgunDSM
  weight: 10
  startingGear: ConscriptShotgunDSMGear
  alwaysUseSpawner: true
  icon: "JobIconImperialLevyman"
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-manatarms
  access:
  - Command
  - Maintenance
  - Service
  - DSMGeneral
  - DSMJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - Empire

- type: startingGear
  id: ConscriptShotgunDSMGear
  equipment:
    head: ClothingHeadHelmetImperialTrooperHelmet
    mask: ClothingMaskImperialCombatGasmask
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    outerClothing: ClothingOuterArmorImperialTrooperArmor
    shoes: ClothingShoesBootsImperialJackboots
    belt: ClothingBeltAssaultFilledShotgun
    gloves: ClothingHandsGlovesImperialLonggloves
    back: WeaponShotgunDSMMatusa
    pocket1: EmergencyOxygenTankFilled
    pocket2: GrenadeShrapnel
    ears: ClothingHeadsetEmpire
    id: LevymanPDA
    suitstorage: WeaponPistolComplianceImperial
