- type: job
  id: Contractor
  name: job-name-contractor
  description: job-description-contractor
  playTimeTracker: JobContractor
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 4000
    - !type:WealthRequirement
      below: 40000
  startingGear: ContractorGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-hire
  accessGroups:
  - GeneralAccess
