- type: job
  id: Contractor
  name: job-name-contractor
  description: job-description-contractor
  playTimeTracker: JobContractor
  requirements:
    - !type:FactionRequirement
      inverted: true
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 4000
    - !type:WealthRequirement
      below: 40000
  startingGear: ContractorGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-hire
  accessGroups:
  - GeneralAccess


- type: startingGear
  id: ContractorGear
  equipment:
    ears: ClothingHeadsetGrey
    id: SpacerPDA
    jumpsuit: ClothingUniformSpacer
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
