- type: job
  id: GliessianDockhand
  name: job-name-gliess-dockhand
  description: job-description-dockhand
  playTimeTracker: JobDockhand
  weight: 20
  requirements:
    - !type:FactionRequirement
      inverted: true
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 10800
  startingGear: DockhandGear
  icon: "JobIconDockhand"
  supervisors: job-supervisors-gliess
  accessGroups:
  - GeneralAccess
  access:
  - GliessSheriff

  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ind-dockhand
      - type: HullrotFaction
        faction: GS
      - type: LanguageAdder
        addSpoken:
          - Tradeband
        addUnderstood:
          - Tradeband

- type: startingGear
  id: DockhandGear
  equipment:
    ears: ClothingHeadsetCMM
    head: ClothingHeadHelmetCMMMachinist
    id: DockhandPDA
    jumpsuit: ClothingUniformJumpsuitCMMMachinist
    belt: ClothingBeltSalvageWebbingFilledNF
    back: ClothingBackpackSHI
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsSalvage
    eyes: ClothingEyesGlassesSunglassesBig
