- type: job
  id: GliessianDeputy
  name: job-name-gliess-deputy
  description: job-description-gliess-deputy
  playTimeTracker: JobContractor
  weight: 30
  startingGear: GliessDeputyGear
  icon: "JobIconMinuteman"
  supervisors: job-supervisors-gliess
  requirements:
    - !type:FactionRequirement
      inverted: true
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 20000
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ind-gliess-deputy
      - type: HullrotFaction
        faction: GS
      - type: LanguageAdder
        addSpoken:
          - Tradeband
        addUnderstood:
          - Tradeband
  accessGroups:
  - GeneralAccess
  access:
  - GliessSheriff
  - GliessDockmaster

- type: startingGear
  id: GliessDeputyGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMM
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatCMMDeputyMarshal
    gloves: ClothingHandsGlovesCombat
    pocket1: WeaponPistolHKUSP
    id: GliessDeputyPDA
    ears: ClothingHeadsetCMM
    neck: ClothingNeckScarfCMMCloak
    outerClothing: ClothingOuterArmorCMMDeputyCarapace
    belt: ClothingBeltMinutemanPouches
  storage:
    belt:
      - Flash
      - Tourniquet
      - MagazinePistol
      - CombatKnife
      - Zipties
