- type: job
  id: GliessianDockmaster
  name: job-name-gliess-dockmaster
  description: job-description-gliess-dockmaster
  playTimeTracker: JobGliessDockmaster
  weight: 50
  startingGear: GliessDockmasterGear
  icon: "JobIconCaptain"
  supervisors: job-supervisors-lols
  requirements:
    - !type:FactionRequirement
      inverted: true
      factionID: "SRM"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 25000
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ind-gliess-dockmaster
      - type: HullrotFaction
        faction: GS
      - type: LanguageAdder
        addSpoken:
          - Tradeband
        addUnderstood:
          - Tradeband
  accessGroups:
  - GeneralAccess
  access:
  - GliessSheriff
  - GliessDockmaster

- type: startingGear
  id: GliessDockmasterGear
  equipment:
    ears: ClothingHeadsetCMM
    shoes: ClothingShoesBootsLaceup
    jumpsuit: ClothingUniformJumpsuitCapFormal
    head: ClothingHeadHatCapcap
    belt: ClothingBeltSheathFilled
    id: GliessDockmasterPDA
    back: ClothingBackpackSatchelLeather
