- type: job
  id: Spacer
  name: job-name-spacer
  description: job-description-spacer
  playTimeTracker: JobSpacer
  startingGear: ContractorGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-hire
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ind-spacer
      - type: LanguageAdder
        addSpoken:
          - Tradeband
        addUnderstood:
          - Tradeband

- type: entity
  parent: IDCardStandard
  id: SpacerIDCard
  name: Spacer ID card
  components:
  - type: Sprite
    layers:
    - state: default
    - state: idpassenger
  - type: PresetIdCard
    job: Spacer


- type: startingGear
  id: ContractorGear
  equipment:
    ears: ClothingHeadsetGrey
    id: SpacerPDA
    jumpsuit: ClothingUniformSpacer
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
