- type: job
  id: Spacer
  name: job-name-spacer
  description: job-description-spacer
  playTimeTracker: JobSpacer
  weight: 10
  startingGear: SpacerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-hire
  requirements:
    - !type:FactionRequirement
      inverted: true
      factionID: "SRM"
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ind-spacer
      - type: HullrotFaction
        faction: IND
      - type: LanguageAdder
        addSpoken:
          - Tradeband
        addUnderstood:
          - Tradeband

- type: startingGear
  id: SpacerGear
  equipment:
    ears: ClothingHeadsetGrey
    id: SpacerPDA
    jumpsuit: ClothingUniformSpacer
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
