- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Security
    min: 36000 # DeltaV - 10 hours
  - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - Shadowkin
        - !type:CharacterTraitRequirement
          traits:
            - ShadowkinBlackeye
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  - Service
  - Detective
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    back: ClothingBackpackSecurityFilledDetective
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatFedoraBrown
    outerClothing: ClothingOuterVestDetective
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  innerClothingSkirt: ClothingUniformJumpskirtDetective
  satchel: ClothingBackpackSatchelSecurityFilledDetective
  duffelbag: ClothingBackpackDuffelSecurityFilledDetective
