# Uniforms
- type: loadout
  id: LoadoutSecurityUniformJumpsuitBlue
  category: Jobs
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
        - SecurityCadet
        - Warden
  items:
    - ClothingUniformJumpsuitSecBlue

- type: loadout
  id: LoadoutSecurityUniformJumpsuitGrey
  category: Jobs
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
        - SecurityCadet
        - Warden
  items:
    - ClothingUniformJumpsuitSecGrey

- type: loadout
  id: LoadoutSecurityUniformJumpskirtGrey
  category: Jobs
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
        - SecurityCadet
        - Warden
  items:
    - ClothingUniformJumpskirtSecGrey

- type: loadout
  id: LoadoutSecurityUniformJumpskirtBlue
  category: Jobs
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
        - SecurityCadet
        - Warden
  items:
    - ClothingUniformJumpskirtSecBlue

- type: loadout
  id: LoadoutSecurityUniformJumpskirtSenior
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
    - !type:CharacterPlaytimeRequirement
      tracker: JobWarden
      min: 21600 # 6 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobDetective
      min: 7200 # 2 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobSecurityOfficer
      min: 21600 # 6 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 216000 # 60 hours
  items:
    - ClothingUniformJumpskirtSeniorOfficer

- type: loadout
  id: LoadoutSecurityUniformJumpsuitSenior
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
    - !type:CharacterPlaytimeRequirement
      tracker: JobWarden
      min: 21600 # 6 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobDetective
      min: 7200 # 2 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobSecurityOfficer
      min: 21600 # 6 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 216000 # 60 hours
  items:
    - ClothingUniformJumpsuitSeniorOfficer

- type: loadout
  id: LoadoutUniformJumpsuitWardenBlue
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - Warden
  items:
    - ClothingUniformJumpsuitWardenBlue

- type: loadout
  id: LoadoutUniformJumpsuitWardenGrey
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - Warden
  items:
    - ClothingUniformJumpsuitWardenGrey

- type: loadout
  id: LoadoutUniformJumpskirtWardenBlue
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Warden
  items:
    - ClothingUniformJumpskirtWardenBlue

- type: loadout
  id: LoadoutUniformJumpskirtWardenGrey
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Warden
  items:
    - ClothingUniformJumpskirtWardenGrey

- type: loadout
  id: LoadoutUniformJumpskirtHoSBlue
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSBlue

- type: loadout
  id: LoadoutUniformJumpskirtHoSGrey
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - HeadOfSecurity
  items:
    - ClothingUniformJumpskirtHoSGrey

- type: loadout
  id: LoadoutUniformJumpsuitSecFormal
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - Detective
        - SecurityOfficer
        - Warden
        - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitSecFormal

- type: loadout
  id: LoadoutUniformJumpsuitSecSummer
  category: Jobs
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - Detective
        - SecurityOfficer
        - Warden
        - HeadOfSecurity
  items:
    - ClothingUniformJumpsuitSecSummer
# Mask
- type: loadout
  id: LoadoutSecurityMaskGasSwat
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Warden
        - HeadOfSecurity
  items:
    - ClothingMaskGasSwat

# Shoes
- type: loadout
  id: LoadoutSecurityShoesJackboots
  category: Jobs
  cost: 1
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Diona
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - Detective
        - SecurityOfficer
        - SecurityCadet
        - Warden
        - HeadOfSecurity
  items:
    - ClothingShoesBootsJack

# Eyes
- type: loadout
  id: LoadoutSecurityEyesHudSecurity
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
        - Warden
        - HeadOfSecurity
        - Brigmedic
  items:
    - ClothingEyesHudSecurity

- type: loadout
  id: LoadoutSecurityEyesEyepatchHudSecurity
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
        - Warden
        - HeadOfSecurity
        - Brigmedic
  items:
    - ClothingEyesEyepatchHudSecurity

- type: loadout
  id: LoadoutSecurityEyesHudSecurityPrescription
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
        - Warden
        - HeadOfSecurity
        - Brigmedic
    - !type:CharacterTraitRequirement
      traits:
        - Nearsighted
  items:
    - ClothingEyesPrescriptionHudSecurity

# Head
- type: loadout
  id: LoadoutSecurityHeadHatBeret
  category: Jobs
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
        - Warden
        - HeadOfSecurity
        - Brigmedic
  items:
    - ClothingHeadHatBeretSecurity

- type: loadout
  id: LoadoutSecurityHeadHelmetInsulated
  category: Jobs
  cost: 3
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - SecurityOfficer
        - Warden
        - HeadOfSecurity
        - Brigmedic
  items:
    - ClothingHeadHelmetInsulated

# Belt
- type: loadout
  id: LoadoutSecurityBeltWebbing
  category: Jobs
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Detective
        - SecurityOfficer
        - SecurityCadet
        - Warden
        - HeadOfSecurity
  items:
    - ClothingBeltSecurityWebbingFilled

# Equipment
- type: loadout
  id: LoadoutSecurityCombatKnife
  category: Jobs
  cost: 1
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Diona
        - Harpy
    - !type:CharacterDepartmentRequirement
      departments:
        - Security
  items:
    - CombatKnife

# TODO: Make this replace the secoff handgun and make it cheaper
# # Species
# - type: loadout
#   id: LoadoutSecurityEquipmentTruncheon
#   category: Jobs
#   cost: 8
#   requirements:
#     - !type:CharacterJobRequirement
#       jobs:
#         - SecurityOfficer
#         - Warden
#         - HeadOfSecurity
#         - Brigmedic
#     - !type:CharacterPlaytimeRequirement
#       tracker: JobSecurityOfficer
#       min: 36000 # 10 hours
#     - !type:CharacterSpeciesRequirement
#       species:
#         - Oni
#   items:
#     - Truncheon
