# Clown
- type: loadout
  id: LoadoutServiceClownOutfitJester
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingUniformJumpsuitJester
    - ClothingHeadHatJester
    - ClothingShoesJester

- type: loadout
  id: LoadoutServiceClownOutfitJesterAlt
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingUniformJumpsuitJesterAlt
    - ClothingHeadHatJesterAlt
    - ClothingShoesJester

- type: loadout
  id: LoadoutServiceClownOuterWinter
  category: JobsServiceUncategorized
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterService
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingOuterWinterClown

- type: loadout
  id: LoadoutServiceClownOuterClownPriest
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterService
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingOuterClownPriest

- type: loadout
  id: LoadoutServiceClownBootsWinter
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutShoesService
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingShoesBootsWinterClown

- type: loadout
  id: LoadoutServiceClownMaskSexy
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMaskService
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingMaskSexyClown

- type: loadout
  id: LoadoutServiceClownBedsheetClown
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutNeckService
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - BedsheetClown

# For the most part we dont want people to take this item, so its used as an example of all the things
# you can do with requirements. Point someone to this thing if they ask "how tf do loadout requirements work?"

- type: loadout
  id: LoadoutServiceClownCowToolboxFilled
  category: JobsServiceUncategorized
  cost: 2
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutEquipmentService
    - !type:CharacterLogicXorRequirement
      requirements:
        - !type:CharacterLogicAndRequirement
          requirements:
            - !type:CharacterSexRequirement
              sex: Male
            - !type:CharacterSpeciesRequirement
              species:
                - Felinid
            - !type:CharacterHeightRequirement
              min: 110
              max: 122
            - !type:CharacterGenderRequirement
              gender: Female
            - !type:CharacterTraitRequirement
              traits:
                - HeavyweightDrunk
        - !type:CharacterLogicAndRequirement
          requirements:
            - !type:CharacterSpeciesRequirement
              species:
                - Harpy
            - !type:CharacterHeightRequirement
              min: 170
            - !type:CharacterWeightRequirement
              min: 20
            - !type:CharacterSexRequirement
              sex: Male
            - !type:CharacterJobRequirement
              inverted: true # This is the equivalent of !(condition)
              jobs:
                - Clown
        - !type:CharacterJobRequirement
          jobs:
            - Clown
  items:
    - CowToolboxFilled

# Mime
- type: loadout
  id: LoadoutServiceMimeOuterWinter
  category: JobsServiceUncategorized
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutOuterService
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - ClothingOuterWinterMime

- type: loadout
  id: LoadoutServiceMimeMaskSad
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMaskService
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - ClothingMaskSadMime

- type: loadout
  id: LoadoutServiceMimeMaskScared
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMaskService
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - ClothingMaskScaredMime

- type: loadout
  id: LoadoutServiceMimeMaskSexy
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMaskService
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - ClothingMaskSexyMime

- type: loadout
  id: LoadoutServiceMimeShoesBootsWinter
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutShoesService
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - ClothingShoesBootsWinterMime

- type: loadout
  id: LoadoutServiceMimeBedsheetMime
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutNeckService
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - BedsheetMime

# Bartender
- type: loadout
  id: LoadoutServiceBartenderUniformPurple
  category: JobsServiceBartender
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Bartender
  items:
    - ClothingUniformJumpsuitBartenderPurple

- type: loadout
  id: LoadoutServiceBartenderArmorDuraVest
  category: JobsServiceBartender
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBartenderOuterwear
    - !type:CharacterJobRequirement
      jobs:
        - Bartender
  items:
    - ClothingOuterArmorDuraVest

- type: loadout
  id: LoadoutServiceBartenderBoxBeanbags
  category: JobsServiceBartender
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBartenderAmmo
    - !type:CharacterJobRequirement
      jobs:
        - Bartender
  items:
    - BoxBeanbag

- type: loadout
  id: LoadoutServiceBartenderBoxLightRifleRubber
  category: JobsServiceBartender
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBartenderAmmo
    - !type:CharacterJobRequirement
      jobs:
        - Bartender
  items:
    - MagazineBoxLightRifleRubber

- type: loadout
  id: LoadoutServiceBartenderShotgunDoubleBarreledRubber
  category: JobsServiceBartender
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBartenderWeapon
    - !type:CharacterJobRequirement
      jobs:
        - Bartender
  items:
    - WeaponShotgunDoubleBarreledRubber

- type: loadout
  id: LoadoutServiceBartenderMosinRubber
  category: JobsServiceBartender
  cost: 3
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutBartenderWeapon
    - !type:CharacterJobRequirement
      jobs:
        - Bartender
  items:
    - WeaponSniperMosinRubber

# Botanist
- type: loadout
  id: LoadoutServiceBotanistUniformOveralls
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Botanist
  items:
    - ClothingUniformOveralls

# Lawyer
- type: loadout
  id: LoadoutServiceLawyerUniformBlueSuit
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerBlue

- type: loadout
  id: LoadoutServiceLawyerUniformBlueSkirt
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerBlue

- type: loadout
  id: LoadoutServiceLawyerUniformRedSuit
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerRed

- type: loadout
  id: LoadoutServiceLawyerUniformRedSkirt
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerRed

- type: loadout
  id: LoadoutServiceLawyerUniformPurpleSuit
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerPurple

- type: loadout
  id: LoadoutServiceLawyerUniformPurpleSkirt
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerPurple

- type: loadout
  id: LoadoutServiceLawyerUniformGoodSuit
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerGood

- type: loadout
  id: LoadoutServiceLawyerUniformGoodSkirt
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerGood

- type: loadout
  id: LoadoutServiceReporterUniformJournalist
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Reporter
  items:
    - ClothingUniformJumpsuitJournalist

# Reporter
- type: loadout
  id: LoadoutServiceReporterUniformDetectivesuit
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Reporter
  items:
    - ClothingUniformJumpsuitDetective

- type: loadout
  id: LoadoutServiceReporterUniformDetectiveskirt
  category: JobsServiceUncategorized
  cost: 0
  exclusive: true
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutUniformsService
    - !type:CharacterJobRequirement
      jobs:
        - Reporter
  items:
    - ClothingUniformJumpskirtDetective

# Musician
- type: loadout
  id: LoadoutItemSynthesizerInstrumentMusician
  category: JobsServiceUncategorized
  cost: 2
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - SynthesizerInstrument

- type: loadout
  id: LoadoutItemMicrophoneInstrumentMusician
  category: JobsServiceUncategorized
  cost: 0
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - MicrophoneInstrument

- type: loadout
  id: LoadoutItemKalimbaInstrumentMusician
  category: Items
  cost: 0
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - KalimbaInstrument

- type: loadout
  id: LoadoutItemTrumpetInstrumentMusician
  category: Items
  cost: 2
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - TrumpetInstrument

- type: loadout
  id: LoadoutItemElectricGuitarInstrumentMusician
  category: Items
  cost: 2
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - ElectricGuitarInstrument

- type: loadout
  id: LoadoutItemBassGuitarInstrumentMusician
  category: Items
  cost: 2
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - BassGuitarInstrument

- type: loadout
  id: LoadoutItemRockGuitarInstrumentMusician
  category: Items
  cost: 2
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - RockGuitarInstrument

- type: loadout
  id: LoadoutItemAcousticGuitarInstrumentMusician
  category: Items
  cost: 2
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - AcousticGuitarInstrument

- type: loadout
  id: LoadoutItemViolinInstrumentMusician
  category: Items
  cost: 2
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - ViolinInstrument

- type: loadout
  id: LoadoutItemHarmonicaInstrumentMusician
  category: Items
  cost: 0
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - HarmonicaInstrument

- type: loadout
  id: LoadoutItemAccordionInstrumentMusician
  category: Items
  cost: 0
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - AccordionInstrument

- type: loadout
  id: LoadoutItemFluteInstrumentMusician
  category: Items
  cost: 0
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - FluteInstrument

- type: loadout
  id: LoadoutItemOcarinaInstrumentMusician
  category: Items
  cost: 0
  requirements:
    - !type:CharacterItemGroupRequirement
      group: LoadoutMusicianInstruments
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - OcarinaInstrument