# Clown
- type: loadout
  id: LoadoutServiceClownOutfitJester
  category: JobsAUncategorized
  cost: 3
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingUniformJumpsuitJester
    - ClothingHeadHatJester
    - ClothingShoesJester

- type: loadout
  id: LoadoutServiceClownOutfitJesterAlt
  category: JobsAUncategorized
  cost: 3
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingUniformJumpsuitJesterAlt
    - ClothingHeadHatJesterAlt
    - ClothingShoesJester

- type: loadout
  id: LoadoutServiceClownOuterWinter
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingOuterWinterClown

- type: loadout
  id: LoadoutServiceClownOuterClownPriest
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingOuterClownPriest

- type: loadout
  id: LoadoutServiceClownBootsWinter
  category: JobsAUncategorized
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Clown
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Diona
        - Harpy
  items:
    - ClothingShoesBootsWinterClown

- type: loadout
  id: LoadoutServiceClownMaskSexy
  category: JobsAUncategorized
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingMaskSexyClown

- type: loadout
  id: LoadoutServiceClownBedsheetClown
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - BedsheetClown

# Mime
- type: loadout
  id: LoadoutServiceMimeOuterWinter
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - ClothingOuterWinterMime

- type: loadout
  id: LoadoutServiceMimeMaskSad
  category: JobsAUncategorized
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - ClothingMaskSadMime

- type: loadout
  id: LoadoutServiceMimeMaskScared
  category: JobsAUncategorized
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - ClothingMaskScaredMime

- type: loadout
  id: LoadoutServiceMimeMaskSexy
  category: JobsAUncategorized
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - ClothingMaskSexyMime

- type: loadout
  id: LoadoutServiceMimeShoesBootsWinter
  category: JobsAUncategorized
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Mime
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Diona
        - Harpy
  items:
    - ClothingShoesBootsWinterMime

- type: loadout
  id: LoadoutServiceMimeBedsheetMime
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Mime
  items:
    - BedsheetMime

# Bartender
- type: loadout
  id: LoadoutServiceBartenderUniformPurple
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Bartender
  items:
    - ClothingUniformJumpsuitBartenderPurple

# Botanist
- type: loadout
  id: LoadoutServiceBotanistUniformOveralls
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
     jobs:
        - Botanist
  items:
    - ClothingUniformOveralls

# Lawyer
- type: loadout
  id: LoadoutServiceLawyerUniformBlueSuit
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
     jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerBlue

- type: loadout
  id: LoadoutServiceLawyerUniformBlueSkirt
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerBlue

- type: loadout
  id: LoadoutServiceLawyerUniformRedSuit
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerRed

- type: loadout
  id: LoadoutServiceLawyerUniformRedSkirt
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerRed

- type: loadout
  id: LoadoutServiceLawyerUniformPurpleSuit
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerPurple

- type: loadout
  id: LoadoutServiceLawyerUniformPurpleSkirt
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerPurple

- type: loadout
  id: LoadoutServiceLawyerUniformGoodSuit
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerGood

- type: loadout
  id: LoadoutServiceLawyerUniformGoodSkirt
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerGood

- type: loadout
  id: LoadoutServiceReporterUniformJournalist
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Reporter
  items:
    - ClothingUniformJumpsuitJournalist

# Reporter
- type: loadout
  id: LoadoutServiceReporterUniformDetectivesuit
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Harpy
    - !type:CharacterJobRequirement
      jobs:
        - Reporter
  items:
    - ClothingUniformJumpsuitDetective

- type: loadout
  id: LoadoutServiceReporterUniformDetectiveskirt
  category: JobsAUncategorized
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Reporter
  items:
    - ClothingUniformJumpskirtDetective

# Musician
- type: loadout
  id: LoadoutItemSynthesizerInstrument
  category: JobsAUncategorized
  cost: 8
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Musician
  items:
    - SynthesizerInstrument
