- type: loadout
  id: LoadoutServiceClownOutfitJester
  category: Jobs
  cost: 3
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingUniformJumpsuitJester
    - ClothingHeadHatJester
    - ClothingShoesJester

- type: loadout
  id: LoadoutServiceClownOutfitJesterAlt
  category: Jobs
  cost: 3
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Clown
  items:
    - ClothingUniformJumpsuitJesterAlt
    - ClothingHeadHatJesterAlt
    - ClothingShoesJester

- type: loadout
  id: LoadoutServiceBartenderUniformPurple
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Bartender
  items:
    - ClothingUniformJumpsuitBartenderPurple

- type: loadout
  id: LoadoutServiceBotanistUniformOveralls
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
     jobs:
        - Botanist
  items:
    - ClothingUniformOveralls

- type: loadout
  id: LoadoutServiceLawyerUniformBlueSuit
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
     jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerBlue

- type: loadout
  id: LoadoutServiceLawyerUniformBlueSkirt
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerBlue

- type: loadout
  id: LoadoutServiceLawyerUniformRedSuit
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerRed

- type: loadout
  id: LoadoutServiceLawyerUniformRedSkirt
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerRed

- type: loadout
  id: LoadoutServiceLawyerUniformPurpleSuit
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerPurple

- type: loadout
  id: LoadoutServiceLawyerUniformPurpleSkirt
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerPurple

- type: loadout
  id: LoadoutServiceLawyerUniformGoodSuit
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpsuitLawyerGood

- type: loadout
  id: LoadoutServiceLawyerUniformGoodSkirt
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Lawyer
  items:
    - ClothingUniformJumpskirtLawyerGood

- type: loadout
  id: LoadoutServiceReporterUniformJournalist
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Reporter
  items:
    - ClothingUniformJumpsuitJournalist

- type: loadout
  id: LoadoutServiceReporterUniformDetectivesuit
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Reporter
  items:
    - ClothingUniformJumpsuitDetective

- type: loadout
  id: LoadoutServiceReporterUniformDetectiveskirt
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - Reporter
  items:
    - ClothingUniformJumpskirtDetective
