- type: job
  id: HospitalityDirector
  name: job-name-hd
  description: job-description-hd
  playTimeTracker: JobHospitalityDirector
  requirements:
  - !type:CharacterPlaytimeRequirement
    tracker: JobJanitor
    min: 14400
  - !type:CharacterPlaytimeRequirement
    tracker: JobReporter
    min: 14400
  - !type:CharacterPlaytimeRequirement
    tracker: JobBotanist
    min: 21600
  - !type:CharacterPlaytimeRequirement
    tracker: JobChef
    min: 21600
  - !type:CharacterPlaytimeRequirement
    tracker: JobBartender
    min: 21600
  - !type:CharacterDepartmentTimeRequirement
    department: Civilian
    min: 72000

  - !type:CharacterEmployerRequirement
    employers:
    - IdrisIncorporated
    - NanoTrasen
    - OrionExpress
  weight: 5
  startingGear: HospitalityGear
  icon: "JobIconHospitalityDirector"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HospitalityDirector 
  - Service
  - Maintenance
  - Janitor
  - Hydroponics
  - Kitchen
  - Bar
  - Musician
  - Theatre
  - Clown
  - Mime
  - Reporter
  - Zookeeper
  - Library 
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff

- type: startingGear
  id: HospitalityGear
  subGear:
  - BartenderPlasmamanGear
  equipment:
    head: ClothingHeadHatBellhopHD
    jumpsuit: ClothingUniformJumpsuitHD
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: HospitalityDirectorPDA
    ears: ClothingHeadsetHeadService #replace this with a command comms service headset when one is added pleaseeeee
    belt: HdTowel

- type: startingGear #this also needs a proper go-over
  id: HospitalityPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitEnviroslacks
    head: ClothingHeadEnvirohelmColorWhite
    gloves: ClothingHandsGlovesEnviroglovesWhite
