- type: job
  id: BoardSHI
  name: job-name-board
  description: job-description-board
  playTimeTracker: JobBoardSHI
  weight: 6
  startingGear: BoardGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconBoard"
  supervisors: job-supervisors-shi
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 18000
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-shi-board
      - type: HullrotFaction
        faction: SHI
      - type: LanguageAdder
        addSpoken:
          - Kaishago
          - Tradeband
        addUnderstood:
          - Kaishago
          - Tradeband
  access:
  - Command
  - Maintenance
  - Shinohara
  - ShinoharaSecurity
  - ShinoharaOfficer
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: BoardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaSuit
    shoes: ClothingShoesBootsLaceup
    neck: ClothingNeckTieRed
    outerClothing: ClothingOuterShinoharaSuitJacket
    id: BoardPDA
    pocket1: TradePassport
    ears: ClothingHeadsetShinohara
    back: ClothingBackpackSHISatchel

- type: job
  id: BoardHRSHI
  name: job-name-boardhr
  description: job-description-boardhr
  playTimeTracker: JobBoardHRSHI
  weight: 7
  startingGear: BoardHRGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconBoard"
  supervisors: job-supervisors-shi
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 14400
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-shi-board
      - type: LanguageAdder
        addSpoken:
          - Kaishago
          - Tradeband
        addUnderstood:
          - Kaishago
          - Tradeband
  access:
  - Command
  - Maintenance
  - Shinohara
  - ShinoharaSecurity
  - ShinoharaOfficer
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: BoardHRGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaHumanResources
    shoes: ClothingShoesBootsLaceup
    neck: ClothingNeckTieRed
    id: BoardPDA
    pocket1: TradePassport
    ears: ClothingHeadsetShinohara
    back: ClothingBackpackSHISatchel
