- type: job
  id: BoardSHI
  name: job-name-board
  description: job-description-board
  playTimeTracker: JobBoardSHI
  weight: 99
  startingGear: BoardGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconBoard"
  supervisors: job-supervisors-shi
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 14400
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-shi-board
      - type: LanguageAdder
        addSpoken:
          - Kaishago
          - Tradeband
        addUnderstood:
          - Kaishago
          - Tradeband
  access:
  - Command
  - Maintenance
  - Shinohara
  - ShinoharaOfficer
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: BoardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaSuit
    shoes: ClothingShoesBootsLaceup
    neck: ClothingNeckTieRed
    outerClothing: ClothingOuterShinoharaSuitJacket
    id: BoardPDA
    pocket1: TradePassport
    ears: ClothingHeadsetShinohara
    back: ClothingBackpackSHISatchel
