- type: job
  id: EmployeeSHI
  name: job-name-employee
  description: job-description-employee
  playTimeTracker: JobEmployeeSHI
  requirements:
    - !type:FactionRequirement
        factionID: "SHI"
  weight: 25
  startingGear: EmployeeGear
  alwaysUseSpawner: true
  icon: "JobIconEmployee"
  requireAdminNotify: false
  supervisors: job-supervisors-shi
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Shinohara
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: EmployeeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaLogistics
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltUtilityEngineering
    outerClothing: ClothingOuterShinoharaVest
    id: EmployeePDA
    pocket1: TradePassport
    ears: ClothingHeadsetShinohara
