- type: job
  id: EmployeeSHI
  name: job-name-employee
  description: job-description-employee
  playTimeTracker: JobEmployeeSHI
  weight: 1
  startingGear: EmployeeGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconEmployee"
  supervisors: job-supervisors-shi
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 0
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-shi-employee
      - type: HullrotFaction
        faction: SHI
      - type: LanguageAdder
        addSpoken:
          - Kaishago
          - Tradeband
        addUnderstood:
          - Kaishago
          - Tradeband
  access:
  - Command
  - Maintenance
  - Shinohara
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: EmployeeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaLogistics
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltUtilityEngineering
    id: EmployeePDA
    pocket1: TradePassport
    ears: ClothingHeadsetShinohara
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterShinoharaVest
    back: ClothingBackpackSHISatchel
