- type: job
  id: ExecutiveSHI
  name: job-name-executive
  description: job-description-executive
  playTimeTracker: JobExecutiveSHI
  weight: 8
  startingGear: ExecutiveGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconExecutive"
  supervisors: job-supervisors-shi
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 36000
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-shi-executive
      - type: HullrotFaction
        faction: SHI
      - type: LanguageAdder
        addSpoken:
          - Kaishago
          - Tradeband
        addUnderstood:
          - Kaishago
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Shinohara
  - ShinoharaOfficer
  - ShinoharaExecutive
  - ShinoharaSecurity

- type: startingGear
  id: ExecutiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitExecutiveShinoharaSuit
    shoes: ClothingShoesBootsLaceup
    neck: ClothingNeckTieRed
    outerClothing: ClothingOuterShinoharaExecSuitJacket
    id: ExecutivePDA
    pocket1: TradePassport
    ears: ClothingHeadsetShinohara
    back: ClothingBackpackSHISatchel
