- type: job
  id: HighsecSHI
  name: job-name-highsec
  description: job-description-highsec
  playTimeTracker: JobHighsecSHI
  weight: 4
  startingGear: HighsecGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconHighsec"
  supervisors: job-supervisors-shi
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 35000
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-shi-corpsec
      - type: HullrotFaction
        faction: SHI
      - type: LanguageAdder
        addSpoken:
          - Kaishago
        addUnderstood:
          - Kaishago
  access:
  - Command
  - Maintenance
  - Shinohara
  - ShinoharaSecurity
  - ShinoharaOfficer
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: HighsecGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaHighsec
    outerClothing: ClothingOuterArmorShinoharaArmorHighsec
    head: ClothingHeadHatShinoharaHelmet
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    id: HighsecPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetShinohara
    pocket1: WeaponPistolLiquidator
    pocket2: TradePassport
    back: ClothingBackpackSHISatchel
    belt: ClothingBeltSecurityFilled
  storage:
    belt:
      - Flash
      - Tourniquet

- type: job
  id: HosSHI
  name: job-name-hos-shi
  description: job-description-hos-shi
  playTimeTracker: JobHosSHI
  weight: 5
  startingGear: HosGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconHighsec"
  supervisors: job-supervisors-shi
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 35000
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-shi-board
      - type: LanguageAdder
        addSpoken:
          - Kaishago
          - Tradeband
        addUnderstood:
          - Kaishago
          - Tradeband
  access:
  - Command
  - Maintenance
  - Shinohara
  - ShinoharaSecurity
  - ShinoharaOfficer
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: HosGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaHOS
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    id: HighsecPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetShinohara
    pocket1: WeaponPistolLiquidator
    pocket2: TradePassport
    back: ClothingBackpackSHISatchel
    head: ClothingHeadHatShinoharaBeretHOS
    mask: ClothingMaskSHIHOSMask
    outerClothing: ClothingOuterArmorShinoharaHOSVest
    belt: ClothingBeltSecurityFilled
  storage:
    belt:
      - Flash
      - Tourniquet
