- type: job
  id: HighsecSHI
  name: job-name-highsec
  description: job-description-highsec
  playTimeTracker: JobHighsecSHI
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 35000
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 39
  startingGear: HighsecGear
  alwaysUseSpawner: true
  icon: "JobIconHighsec"
  requireAdminNotify: false
  supervisors: job-supervisors-shi
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-shi-highsec
      - type: LanguageAdder
        addSpoken:
          - Kaishago
        addUnderstood:
          - Kaishago
  access:
  - Command
  - Maintenance
  - Shinohara
  - ShinoharaSecurity
  - ShinoharaOfficer
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: HighsecGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaHighsec
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesCombat
    id: HighsecPDA
    ears: ClothingHeadsetShinohara
    pocket1: Handcuffs
    pocket2: TradePassport
    back: ClothingBackpackSHISatchel
