- type: job
  id: MedtechSHI
  name: job-name-medtech
  description: job-description-medtech
  playTimeTracker: JobMedtechSHI
  requirements:
    - !type:FactionRequirement
      factionID: "SHI"
  weight: 25
  startingGear: MedtechGear
  alwaysUseSpawner: true
  icon: "JobIconMedtech"
  requireAdminNotify: false
  supervisors: job-supervisors-shi
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Shinohara
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: MedtechGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaDoctor
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterShinoharaLabcoat
    id: MedtechPDA
    pocket1: TradePassport
    eyes: ClothingEyesGlassesChemical
    ears: ClothingHeadsetShinohara
