- type: job
  id: MedtechSHI
  name: job-name-medtech
  description: job-description-medtech
  playTimeTracker: JobMedtechSHI
  weight: 2
  startingGear: MedtechGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconMedtech"
  supervisors: job-supervisors-shi
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: LanguageKnowledge
        speaks:
          - Tradeband
          - TauCetiBasic
        understands:
          - Tradeband
          - TauCetiBasic
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 1.5
  access:
  - Command
  - Maintenance
  - Shinohara
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: MedtechGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaDoctor
    shoes: ClothingShoesColorWhite
    id: MedtechPDA
    pocket1: TradePassport
    eyes: ClothingEyesGlassesChemical
    ears: ClothingHeadsetShinohara
