- type: job
  id: MedtechSHI
  name: job-name-medtech
  description: job-description-medtech
  playTimeTracker: JobMedtechSHI
  weight: 2
  startingGear: MedtechGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconMedtech"
  supervisors: job-supervisors-shi
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:FactionRequirement
      factionID: "SHI"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 1.75
      - type: ChatRank
        rank: crescent-rank-shi-medtech
      - type: HullrotFaction
        faction: SHI
      - type: LanguageAdder
        addSpoken:
          - Kaishago
        addUnderstood:
          - Kaishago
  access:
  - Command
  - Maintenance
  - Shinohara
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: MedtechGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitShinoharaDoctor
    shoes: ClothingShoesBootsJack
    id: MedtechPDA
    pocket1: TradePassport
    eyes: ClothingEyesGlassesChemical
    ears: ClothingHeadsetShinohara
    gloves: ClothingHandsGlovesLatex
    outerClothing: ClothingOuterCoatLab
    back: ClothingBackpackSHISatchel
