- type: faction
  name: "Divine Sol Mandate"
  id: DSM
  descriptionPrefix: |
    MINIMUM PLAYTIME: NONE
    One of the two major players in the Taypan Sector.
    Good for new players, and represents the core Hullrot experience.
  buttonColor: DarkSlateBlue
  description: |
    A neo-feudalistic remnant of an Empire that once stretched across the stars, much akin to the ancient Holy Roman Empire.
    Now what remains is mostly isolated to the sector, sent out by the divine Kaiser to secure this starzone from an
    incompetent Noble who allowed it to get infested by the Socialist scourge now known as the New Crescent Workers League.
    For decades, these two giants have clashed over the control of the Sector, each facing their own share of victory and defeat.
    The carrier known as the Countsman ventures into Taypan to secure a foothold and to kick out the Unionist forces once again.

    The Divine Sol Mandate prays to the Saints and, most importantly, the Kaiser for their victory. Most higher roles are taken by
    members of noble houses with varied standing within the Mandate, while House Kircheis sits at the top. The House of Questions
    keeps the servants of the Mandate ever vigilant, as they are quick to act on any sign of disloyalty or treason.
    Freeholders or even nobles, who think that they can speak up against the current regime, quickly find themselves under
    the watchful eye of the HoQ, pressured into silence, or never heard from again. Other races are permitted within Imperial ranks,
    but are often subject to increased scrutiny and formal or informal discrimination. The Atyrians take the brunt of this hate,
    as even the Unathi are seen ridiculing them.
  color: "#9FED58"
  weight: 8
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: dsm

- type: faction
  name: "New Crescent Worker's League"
  id: NCWL
  descriptionPrefix: |
    MINIMUM PLAYTIME: NONE
    One of the two major players in the Taypan Sector.
    Good for new players, and represents the core Hullrot experience.
  buttonColor: "#a46106"
  description: |
    A militant syndicalist government born out of revolt against House Olywir. They have now grown into a major power within the
    isolated sector, capable of rivaling the Divine Sol Mandate. They operate out of their frontline station, Port Belreska,
    waging a decades-long war against the Imperial dogs that seek to subjugate them once more. They are made up of several
    workers' unions, but those fighting at the front are members of the Homeguard, led by the iron-willed Volgin Grishingrad.

    The New Crescent Workers League seeks equality and freedom for all workers of the Crescent, no matter their species.
    Their strong beliefs were forged from the harsh quotas imposed by House Olywir and the oppression imposed on the unions.
    At one point, the League managed to bring liberation to the entire Sector, finally deposing House Olywir,
    but that victory was short-lived, as much of their gains were reversed by the arrival of House Kircheis.
    After many years of war, cracks are finally showing, but the few dissenters that exist dare not show their face,
    lest they be taken in by the Ministry of Internal Vigilance and Discipline.

  color: "#9FED58"
  weight: 7
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: ncwl

- type: faction
  name: "Shinohara Heavy Industries"
  id: SHI
  descriptionPrefix: |
    MINIMUM PLAYTIME: 3 HOURS / 1 ROUND
    An industrial giant, with trade-heavy gameplay and high tech.
    Expect heavy profit quotas, pirate raids and little support.
  buttonColor: DarkSlateGray
  description: |
    The last corporate giant standing. A reminder and a relic of the old world. Shinohara Heavy Industries is the last
    'real corporation' in the present day. Cut off from the main bubble, where they rule a huge swathe of space under the
    guise of the New American Protectorate, their corporate dogma remains. Coming from an era once run by corporations,
    a world of unparalleled greed, innovation, progress, and efficiency - to most, Shinohara's ways are more 'alien' than actual
    alien species. Being the largest player in the field of archaeotechnology, it is the holder of many rediscovered and
    reverse-engineered technologies from the now-defunct NanoTrasen Industries, putting SHI as the unmatched and unrivaled
    corporate powerhouse in the Sector.

    Their fingers are in every pie. they manage logistics between systems, tech scavenging, resource mining operations,
    and even dabble in the manufacturing of space-capable vessels. While they mainly operate out of the
    Prometheus Shipyards, Tatsumoto is used to represent their interests and sell their wares to all sides.
    Situated within a contested system between the League and the Mandate, including the Taypani Freestations Coalition's
    preying presence, Shinohara has been forced into a spiral of 'Strategic Trade Relations,'
    'Kinetic Preservation of Corporate Interests,' and 'Competitive Partnership Management.'
  color: "#9FED58"
  weight: 6
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: shi

- type: faction
  name: "Taypani Freestations Coalition"
  id: TFSC
  descriptionPrefix: |
    MINIMUM PLAYTIME: 3 HOURS / 1 ROUND
    Four individual corporations united under one flag, for profit and freedom.
    Other factions may offer contracts or ask for your services.
    Other factions may be suspicious or immediately hostile.
    Your allies may betray you for a higher paycheck.
  buttonColor: DarkRed
  description: |
    A loose conglomerate of independent groups made up of pirates, privateers, shipbreakers,
    and predatory medical professionals with little to no qualms about taking your organs for themselves.
    The most prominent groups are Gorlex Security Consulting, Interdyne Pharmaceuticals, Cyberdawn Technologies,
    and Shipfitters Astronautics Workers Union. Each of them offers certain expertise and profits from it;
    sometimes, they are compared to a scavenger ecosystem for how they operate.

    They were born from the old New Crescent Syndicate of Privateers, a faction formed by Mandate and League defectors
    who wished to live away from the grip of the major factions. They were mostly pirates and privateers whom the major
    players in the sector did not look kindly upon and hunted them down with prejudice. Those privateers who saw the coming end
    formed the Taypani Freestations Coalition, focusing more on providing their varied array of services rather than simply
    pillaging. But with the destruction of Freeport, these groups have drifted apart even more, often fighting each other.
  color: "#9FED58"
  weight: 5
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: tfsc

- type: faction
  name: "The Taypani-Atyrian Pact"
  id: TAP
  descriptionPrefix: |
    MINIMUM PLAYTIME: 10 HOURS / 3 ROUNDS
    This faction has only a very small outpost in the Taypan system.
    A small, hidden station with only four roles is their only presence.
    Play at your own risk.
  buttonColor: DarkGreen
  description: |
    A loosely organized tribal community of nomadic starfarers, the Taypani-Atyrian Pact consists of several nomadic
    families of various racial backgrounds. Primarily made up of the spiritual Arabet, the militaristic Al'Seik,
    the materialistic Izdari, and the scrappy Thukker families, they operate out of a converted capital freighter,
    moving from site to site to eke out a living. Most nomads carry the foul reputations of mercenaries, lowlives,
    smugglers, racketeers, and gamblers.
  color: "#9FED58"
  weight: 4
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: fourfamilies

- type: faction
  name: "Saint Romaine's Militia"
  id: SRM
  descriptionPrefix: |
    MINIMUM PLAYTIME: 10 HOURS / 3 ROUNDS
    This faction is only very rarely present in the Taypan system.
    Restricted to Special Midround Spawns
  buttonColor: Black
  description: |
    Formerly several fireteams of the Imperial Compliance Corps united under a single wing, the SRM have
    found their new identity in the reclamation of escaped Imperial 'assets', as well as the 'conscription'
    of new ones. Essentially a slaver's guild with a self-appointed divine edge, they operate out of the
    Domain system under their Imperial overlords, but often stray into Taypan to capture victims for
    the rebuilding effort.
  color: "#9FED58"
  weight: 3
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: srm

- type: faction
  name: "Central Sol Authority"
  id: ATH
  descriptionPrefix: |
    MINIMUM PLAYTIME: 10 HOURS / 3 ROUNDS
    This faction is only very rarely present in the Taypan system.
    Restricted to Special Midround Spawns
  buttonColor: Black
  description: |
    An oligarchic authoritarian regime, the successor state to the old Mandate, that could now be best described as fascist.
    They are held responsible for the death of the old Kaiser and have been fighting a civil war for decades.
    Often known as simply the Authoritat, they were born out of the greed of the former Imperial court. Led by the Jovian
    ideals of psionic purity, the Authoritat has minimal interest in feudal reign like their precursors, instead focusing on
    controlling the populace and on violent conquests made to eradicate species and communities that they've found to be linked
    to the Boundary, Taypan, and other psionic phenomena. It is believed by Authoritat officials that the source of the
    Boundary itself comes from the combined, manifested thought of all psionically-enabled people in the Imperial Supercluster,
    and with every spell cast, every psionicist born, it only becomes larger and more aggressive, threatening to consume the galaxy.

    Effectively, the prime superpower of all of humanity, the Authoritat allows for a good amount of economic freedom for its
    non-psionic populace and promotes loyalty in a manner not too dissimilar to the Prussian traditions of old Earth,
    with aspiring members climbing up the military ladder of different units, such as the 43rd Battlegroup of the Sol system.
    Dissenters who think they can speak up against the current regime quickly find themselves screened and detained.
    Tight information control prevents widespread dissent, and officials often rewrite history itself to suit the needs of the
    Authoritat.
  color: "#ffffed"
  weight: 2
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: csa

- type: faction
  name: "Colonial Minutemen"
  id: TSP
  description: |
    Appointed by themselves as a civil enforcement agency, the Colonial Minutemen are a frontier sheriff agency
    run solely on scant funding from confiscated items and donations from private and civilian entities.
    Formed with the system's best interests at heart, underperforming equipment, underfunded staff, and
    tendency to draw their members from within impoverished circles leave them susceptible to corruption - which
    the major powers of the system often has little manpower or resources to mitigate or mend.
  color: "#9FED58"
  weight: 1
  enabled: false
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: tsp
