- type: job
  id: CoordinatorNCSP
  name: job-name-coordinator
  description: job-description-coordinator
  playTimeTracker: JobCoordinatorNCSP
  weight: 8
  startingGear: CoordinatorGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconSyndieCoordinator"
  supervisors: You answer to the interests of the Interdyne Pharmaceuticals company. Organize your employees. Secure stakeholders and profit.
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-coordinator
      - type: HullrotFaction
        faction: IPM
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 2.5
      - type: LanguageAdder
        addSpoken:
          - Freespeak
          - Tradeband
        addUnderstood:
          - Freespeak
          - Tradeband
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateInterdyne
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: CoordinatorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateInterdyneWhiteUniform
    gloves: ClothingHandsGlovesCombat
    mask: ClothingMaskSyndicateFacemask
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatSyndicateInterdyneBeret
    id: CoordinatorPDA
    ears: ClothingHeadsetNCSPInterdyne
    pocket1: AccessElevatorIPM
    pocket2: WeaponPistolHKUSP
    back: ClothingBackpackNCSP
  storage:
    back:
      - Flash
      - Tourniquet
      - Zipties
      - MagazinePistol
      - CombatKnife
