- type: job
  id: ForemanNCSP
  name: job-name-foreman
  description: job-description-foreman
  playTimeTracker: JobForemanNCSP
  weight: 2
  startingGear: ForemanGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconSyndieForeman"
  supervisors: You're the leader of the SAW. You answer to your own interests
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-foreman
      - type: HullrotFaction
        faction: SAW
      - type: LanguageAdder
        addSpoken:
          - Freespeak
          - Tradeband
        addUnderstood:
          - Freespeak
          - Tradeband
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateSaws
  - SyndicateCommand
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ForemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSaws
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatHardhatSyndicateForeman
    id: ForemanPDA
    ears: ClothingHeadsetNCSPSaws
    outerClothing: ClothingOuterArmorSyndicateForeman
    belt: ClothingBeltUtilityEngineering
    back: ClothingBackpackNCSPFilledInfanteer
    pocket1: WeaponPistolViperWood
    gloves: ClothingHandsGlovesFingerless
    pocket2: AccessElevatorSAW
