- type: job
  id: ForemanNCSP
  name: job-name-foreman
  description: job-description-foreman
  playTimeTracker: JobForemanNCSP
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-foreman

  weight: 8
  startingGear: ForemanGear
  alwaysUseSpawner: true
  icon: "JobIconSyndieForeman"
  requireAdminNotify: true
  supervisors: You're the leader of the SAW. You answer to your own interests
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateSaws
  - SyndicateCommand
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ForemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSaws
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatHardhatSyndicateForeman
    id: ForemanPDA
    ears: ClothingHeadsetNCSPSaws
    outerClothing: ClothingOuterArmorSyndicateForeman
    belt: ClothingBeltUtilityEngineering
    back: ClothingBackpackNCSPFilledInfanteer
    pocket1: WeaponPistolHKUSP
    gloves: ClothingHandsGlovesFingerless
    pocket2: AccesElevatorSAW
