- type: job
  id: InfanteerNCSP
  name: job-name-infanteer
  description: job-description-infanteer
  playTimeTracker: JobInfanteerNCSP
  weight: 10
  startingGear: InfanteerGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconSyndiePrivateer"
  supervisors: You answer to the Ringleader and Gorlex Security Lieutenants
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-op
      - type: HullrotFaction
        faction: GSC
      - type: LanguageAdder
        addSpoken:
          - Freespeak
        addUnderstood:
          - Freespeak
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateGorlex
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: InfanteerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicate
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHelmetSyndicateBasic
    id: InfanteerPDA
    ears: ClothingHeadsetNCSP
    belt: ClothingBeltSyndicateWebbing
    outerClothing: ClothingOuterArmorSyndicateArmorvest
    pocket1: WeaponPistolViperWood
    pocket2: ClothingMaskGasSyndicate
    gloves: ClothingHandsGlovesFingerless
    back: ClothingBackpackNCSP
  storage:
    belt:
      - Flash
      - Tourniquet
      - MagazinePistol
      - CombatKnife
      - Zipties
