- type: job
  id: InfanteerNCSP
  name: job-name-infanteer
  description: job-description-infanteer
  playTimeTracker: JobInfanteerNCSP
  weight: 10
  startingGear: InfanteerGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconSyndiePrivateer"
  supervisors: You answer to the Ringleader and Gorlex Security Lieutenants
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 8000
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-pfc
      - type: LanguageAdder
        addSpoken:
          - Freespeak
        addUnderstood:
          - Freespeak
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateGorlex
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: InfanteerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicate
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHelmetSyndicateBasic
    id: InfanteerPDA
    ears: ClothingHeadsetNCSP
    belt: ClothingBeltSyndicateWebbing
    pocket1: WeaponPistolHKUSP
    gloves: ClothingHandsGlovesFingerless
    back: ClothingBackpackNCSP
  storage:
    back:
    - id: Flash
    - id: Tourniquet
    - id: Zipties
    - id: MagazinePistol
    - id: CombatKnife
