- type: job
  id: IntelligenceOfficerNCSP
  name: job-name-intelligenceofficer
  description: job-description-intelligenceofficer
  playTimeTracker: JobIntelligenceOfficerNCSP
  weight: 5
  startingGear: IntelligenceOfficerGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconSyndieIntelligenceOfficer"
  supervisors: You answer to the interests of the CyberDawn Technologies company. Protect your technology, make money,  take out competition.
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:SexRequirement
      sex: Male
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
      - type: NukeOperative
        rank: crescent-rank-patriarch
      - type: HullrotFaction
        faction: CD
      - type: LanguageAdder
        addSpoken:
          - Freespeak
          - SolCommon
          - Tradeband
          - RobotTalk # one of the main facets of  cybersun was AI so they probably understand it
        addUnderstood:
          - Freespeak
          - SolCommon
          - Tradeband
          - RobotTalk
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateRamzi
  - SyndicateCommand
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: IntelligenceOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSuitCyberdawn
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatPatriarch
    id: IntelligenceOfficerPDA
    back: ClothingBackpackNCSPFilledInfanteer
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorCyberdawnPatriarch
    ears: ClothingHeadsetNCSPCyberdawn
    pocket1: AccessElevatorCD
