- type: job
  id: LieutenantNCSP
  name: job-name-lieutenant
  description: job-description-lieutenant
  playTimeTracker: JobLieutenantNCSP
  weight: 11
  startingGear: LieutenantGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconSyndieLieutenant"
  supervisors: You answer to the Ringleader.
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 30000
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-boss
      - type: HullrotFaction
        faction: GSC
      - type: LanguageAdder
        addSpoken:
          - Freespeak
          - Tradeband
        addUnderstood:
          - Freespeak
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - SyndicateBasic
  - SyndicateCommand
  - SyndicateGorlex

- type: startingGear
  id: LieutenantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateOfficer
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterArmorSyndicateLieutenant
    id: LieutenantPDA
    ears: ClothingHeadsetNCSP
    pocket1: WeaponPistolViperWood
    pocket2: ClothingMaskGasSyndicate
