- type: job
  id: OperativeNCSP
  name: job-name-operative
  description: job-description-operative
  playTimeTracker: JobOperativeNCSP
  weight: 4
  startingGear: OperativeGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconSyndieOperative"
  supervisors: You answer to the patriarch and the interests of the CyberDawn Technologies company.
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 0
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
      - type: NukeOperative
        rank: crescent-rank-operative
      - type: HullrotFaction
        faction: CD
      - type: LanguageAdder
        addSpoken:
          - Freespeak
          - SolCommon
        addUnderstood:
          - Freespeak
          - SolCommon
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateRamzi
  - Engineering
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: OperativeGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSoldierCyberdawn
    shoes: ClothingShoesBootsCombat
    id: OperativePDA
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterArmorKendoBogu
    ears: ClothingHeadsetNCSPCyberdawn
    back: ClothingBackpackNCSP
    pocket1: WeaponPistolAnsem
    belt: ClothingBeltSyndicateWebbing
  storage:
    belt:
      - Flash
      - Tourniquet
      - MagazinePistolHeavy
      - CombatKnife
      - Zipties
