- type: job
  id: CyberdawnTechNCSP
  name: job-name-cyberdawntech
  description: job-description-cyberdawntech
  playTimeTracker: JobCyberdawnTechNCSP
  weight: 3
  startingGear: CyberdawnGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconCyberdawnTech"
  supervisors: You answer to the patriarch and the interests of the CyberDawn Technologies company.
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 0
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
      - type: NukeOperative
        rank: crescent-rank-doc
      - type: HullrotFaction
        faction: CD
      - type: LanguageAdder
        addSpoken:
          - Freespeak
          - SolCommon
          - RobotTalk # one of the main facets of cybersun was AI so they probably understand it
        addUnderstood:
          - Freespeak
          - SolCommon
          - RobotTalk
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateRamzi
  - Engineering
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: CyberdawnGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateLabCyberdawn
    shoes: ClothingShoesBootsCombat
    id: CyberdawnTechPDA
    ears: ClothingHeadsetNCSPCyberdawn
    back: ClothingBackpackNCSPFilledInfanteer
    gloves: ClothingHandsGlovesFingerless
