- type: job
  id: CyberdawnTechNCSP
  name: job-name-cyberdawntech
  description: job-description-cyberdawntech
  playTimeTracker: JobCyberdawnTechNCSP
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 2000
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-syndoc
  weight: 15
  startingGear: CyberdawnGear
  alwaysUseSpawner: true
  icon: "JobIconCyberdawnTech"
  requireAdminNotify: false
  supervisors: You answer to the patriach and the interests of the CyberDawn Technologies company.
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateRamzi
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: CyberdawnGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateLabCyberdawn
    shoes: ClothingShoesBootsCombat
    id: CyberdawnTechPDA
    ears: ClothingHeadsetNCSPCyberdawn
    back: ClothingBackpackNCSPFilledInfanteer
    gloves: ClothingHandsGlovesFingerless
