- type: job
  id: RipperdocNCSP
  name: job-name-ripperdoc
  description: job-description-ripperdoc
  playTimeTracker: JobRipperdocNCSP
  weight: 6
  startingGear: RipperdocGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconSyndieRipperdoc"
  supervisors: You answer to the interests of the Interdyne Pharmaceuticals company's coordinator and your peers.
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 0
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-doc
      - type: HullrotFaction
        faction: IPM
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 1.75
      - type: LanguageAdder
        addSpoken:
          - Freespeak
        addUnderstood:
          - Freespeak
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateInterdyne
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: RipperdocGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateInterdyneScrubs
    shoes: ClothingShoesBootsCombat
    id: RipperdocPDA
    ears: ClothingHeadsetNCSPInterdyne
    mask: ClothingMaskSyndicateFacemask
    pocket1: WeaponPistolHKUSP
    pocket2: MedkitCombatFilled
    back: ClothingBackpackNCSP
  storage:
    back:
      - Flash
      - Tourniquet
      - Zipties
      - MagazinePistol
      - CombatKnife
