- type: job
  id: ShipbreakerNCSP
  name: job-name-shipbreaker
  description: job-description-shipbreaker
  playTimeTracker: JobShipbreakerNCSP
  weight: 1
  startingGear: ShipbreakerGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconSyndieShipbreaker"
  supervisors: You answer to the Shipfitters Aerodynamic & Worker's union interests and its foreman's.
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 0
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-saw
      - type: HullrotFaction
        faction: SAW
      - type: LanguageAdder
        addSpoken:
          - Freespeak
        addUnderstood:
          - Freespeak
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateSaws
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ShipbreakerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSaws
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatHardhatSyndicate
    id: ShipbreakerPDA
    ears: ClothingHeadsetNCSPSaws
    belt: ClothingBeltUtilityEngineering
    pocket1: WeaponPistolViperWood
    gloves: ClothingHandsGlovesFingerless
    back: ClothingBackpackNCSPSatchelFilledInfanteer
