- type: job
  id: ShipbreakerNCSP
  name: job-name-shipbreaker
  description: job-description-shipbreaker
  playTimeTracker: JobShipbreakerNCSP
  weight: 1
  startingGear: ShipbreakerGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconSyndieShipbreaker"
  supervisors: You answer to the Shipfitters Aerodynamic & Worker's union interests, which your Foreman will decide.
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Blindness
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-saw
      - type: LanguageKnowledge
        speaks:
          - Freespeak
          - TauCetiBasic
        understands:
          - Freespeak
          - TauCetiBasic
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateSaws
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ShipbreakerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateSaws
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatHardhatSyndicate
    id: ShipbreakerPDA
    ears: ClothingHeadsetNCSPSaws
    belt: ClothingBeltUtilityEngineering
    pocket1: WeaponPistolHKUSP
    gloves: ClothingHandsGlovesFingerless
    back: ClothingBackpackNCSPSatchelFilledInfanteer
