- type: job
  id: TechnicianNCSP
  name: job-name-technician
  description: job-description-technician
  playTimeTracker: JobTechnicianNCSP
  weight: 9
  startingGear: TechnicianGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconSyndieNewblood"
  supervisors: You answer to the Ringleader of the New Crescent Syndicate Privateers.
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 21600 # 6 hours
      inverted: true # Leave slots open for newer, less confident players.
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-op
      - type: LanguageAdder
        addSpoken:
          - Freespeak
        addUnderstood:
          - Freespeak
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateGorlex
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: TechnicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicate
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatSyndicateArmaments
    id: InfanteerPDA
    back: ClothingBackpackNCSPSatchelFilledInfanteer
    ears: ClothingHeadsetNCSP
    pocket1: WeaponPistolViperWood
