- type: job
  id: TraumasecNCSP
  name: job-name-traumasec
  description: job-description-traumasec
  playTimeTracker: JobTraumasecNCSP
  weight: 7
  startingGear: TraumasecGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconSyndieTraumasec"
  supervisors: You answer to the interests of the Interdyne Pharmaceuticals company's coordinator and your peers.
  canBeAntag: false
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:FactionRequirement
      factionID: "TFSC"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-agent
      - type: HullrotFaction
        faction: IPM
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 1.75
      - type: LanguageAdder
        addSpoken:
          - Freespeak
        addUnderstood:
          - Freespeak
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateInterdyne
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: TraumasecGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateInterdyne
    gloves: ClothingHandsGlovesFingerless
    mask: ClothingMaskBreathMedicalSecurity
    shoes: ClothingShoesBootsCombat
    id: TraumasecPDA
    pocket1: WeaponPistolHKUSP
    ears: ClothingHeadsetNCSPInterdyne
    belt: ClothingBeltSyndicateWebbingInterdyne
  storage:
    belt:
      - Flash
      - Tourniquet
      - MagazinePistol
      - CombatKnife
      - Zipties
