- type: job
  id: PhysicianCMM
  name: job-name-physician
  description: job-description-physician
  playTimeTracker: JobPhysicianCMM
  weight: 24
  startingGear: PhysicianGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconCMMPhysician"
  supervisors: You answer to your Colonial Marshal, Deputy Marshal and Watchmaster.
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
        factionID: "TSP"
    - !type:CharacterTraitRequirement
        inverted: true
        traits:
          - Blindness
          - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-physician
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 1.75
  access:
  - Command
  - Maintenance
  - Minuteman
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: PhysicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMPhysician
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatMinuteman
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    id: PhysicianPDA
    ears: ClothingHeadsetCMM
    pocket1: WeaponPistolHKUSP
