- type: job
  id: DeputyMarshalCMM
  name: job-name-deputymarshal
  description: job-description-deputymarshal
  playTimeTracker: JobDeputyMarshalCMM
  weight: 32
  startingGear: DeputyMarshalGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconDeputyMarshal"
  supervisors: You answer to your Colonial Marshal.
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 36000
    - !type:FactionRequirement
        factionID: "TSP"
    - !type:CharacterTraitRequirement
        inverted: true
        traits:
          - Muted
          - Blindness
          - Pacifist
          - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-2ic
  access:
  - Command
  - Maintenance
  - Minuteman
  - MinutemanPrison
  - MinutemanRankingOfficer
  - MinutemanMarshal
  - CMMFunds
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: DeputyMarshalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMOfficer
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatCMMDeputyMarshal
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    pocket1: WeaponRevolverSnubnose
    id: DeputyMarshalPDA
    ears: ClothingHeadsetCMM
    outerClothing: ClothingOuterArmorCMMDeputyCarapace
