- type: job
  id: MarshalCMM
  name: job-name-marshal
  description: job-description-marshal
  playTimeTracker: JobMarshalCMM
  weight: 39
  startingGear: MarshalGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconMarshal"
  supervisors: You answer to your heart's contempt, whether it be protecting the sector's civilians or aiding criminal organizations.
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
        factionID: "TSP"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-marshallie
  access:
  - Command
  - Maintenance
  - Minuteman
  - MinutemanPrison
  - MinutemanRankingOfficer
  - MinutemanMarshal
  - CMMFunds
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: MarshalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMOfficer
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatCMMMarshal
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    pocket1: WeaponRevolverSnubnose
    id: MarshalPDA
    ears: ClothingHeadsetCMM
    outerClothing: ClothingOuterArmorCMMCarapace
