- type: job
  id: MinutemanCMM
  name: job-name-minuteman
  description: job-description-minuteman
  playTimeTracker: JobMinutemanCMM
  weight: 26
  startingGear: MinutemanGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconMinuteman"
  supervisors: You answer to your Colonial Marshal, Deputy Marshal and Watchmaster.
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
        factionID: "TSP"
    - !type:CharacterTraitRequirement
        inverted: true
        traits:
          - Muted
          - Blindness
          - Pacifist
          - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-minuteman
  access:
  - Command
  - Maintenance
  - Minuteman
  - MinutemanPrison
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: MinutemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMM
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatMinuteman
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    pocket1: WeaponPistolHKUSP
    id: MinutemanPDA
    ears: ClothingHeadsetCMM
    neck: ClothingNeckScarfCMMCloak
    outerClothing: ClothingOuterArmorCMM
