- type: job
  id: OrdnancemanCMM
  name: job-name-ordnanceman
  description: job-description-ordnanceman
  playTimeTracker: JobOrdnancemanCMM
  weight: 18
  startingGear: OrdnancemanGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconOrdnanceman"
  supervisors: You answer to your Colonial Marshal , Deputy Marshal and Watchmaster.
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
        factionID: "TSP"
    - !type:CharacterTraitRequirement
        inverted: true
        traits:
          - Blindness
          - Pacifist
          - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ordnance
  access:
  - Command
  - Maintenance
  - Minuteman
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: OrdnancemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMOrdnanceman
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHelmetCMMOrdnanceman
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    id: OrdnancemanPDA
    ears: ClothingHeadsetCMM
    pocket1: WeaponPistolHKUSP
