- type: job
  id: WatchmasterCMM
  name: job-name-watchmaster
  description: job-description-watchmaster
  playTimeTracker: JobWatchmasterCMM
  weight: 28
  startingGear: WatchmasterGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconWatchmaster"
  supervisors: You answer to your Colonial Marshal and the Deputy Marshal
  canBeAntag: false
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 12000
  - !type:FactionRequirement
      factionID: "TSP"
  - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-watchmaster
  access:
  - Command
  - Maintenance
  - Minuteman
  - MinutemanPrison
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: WatchmasterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMMOfficer
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHatWatchmaster
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltMinutemanPouches
    pocket1: WeaponPistolHKUSP
    id: WatchmasterPDA
    ears: ClothingHeadsetCMM
    neck: ClothingNeckScarfCMMCloak
    outerClothing: ClothingOuterArmorCMM
