- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 24000
  - !type:CharacterDepartmentTimeRequirement
    department: Engineering
    min: 48800
  - !type:CharacterPlaytimeRequirement
    tracker: JobStationEngineer
    min: 36000 # 10 hours
  - !type:CharacterPlaytimeRequirement
    tracker: JobAtmosphericTechnician
    min: 36000 # 10 hours
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Foreigner
    - ForeignerLight
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
    - ZavodskoiInterstellar
    - HephaestusIndustries
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellPotato

- type: startingGear
  id: ChiefEngineerGear
  subGear:
  - ChiefEngineerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
    back: ClothingBackpackEngineering
    shoes: ClothingShoesColorBrown
    id: CEPDA
    ears: ClothingHeadsetAltEngineering
  storage:
    back:
    - Flash

- type: startingGear
  id: ChiefEngineerPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitChiefEngineer
    head: ClothingHeadEnvirohelmChiefEngineer
    gloves: ClothingHandsGlovesEnviroglovesChiefEngineer
