- type: job
  id: TechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
  startingGear: TechnicalAssistantGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Maintenance
  - Engineering
  - External
  requirements:
    - !type:CharacterEmployerRequirement
      inverted: true
      employers:
      - Unemployed

- type: startingGear
  id: TechnicalAssistantGear
  subGear:
  - StationEngineerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorYellow
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: TechnicalAssistantPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    pocket2: BookEngineersHandbook
  innerClothingSkirt: ClothingUniformJumpskirtColorYellow
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
