#IF YOURE WONDERING WHERE ALL THE NON-CONSCRIPT JOBS WENT
#JUST RE-ENABLE THEM AND SET editorHidden: false
#YOU'RE WELCOME
# .2 - 2025

- type: department
  id: Logistics
  description: department-Cargo-description
  color: "#A46106"
  weight: -90
  primary: false
  editorHidden: true

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: 5
  roles:
  - GliessianDockmaster
  - GliessianSheriff
  - GliessianDeputy
  - Spacer
  - GliessianDockhand
  editorHidden: false

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - CentralCommandOfficial
  - HeadOfPersonnel # Not shown but needed here for playtime
  - HeadOfSecurity # Not shown but needed here for playtime
#  - ChiefMedicalOfficer
  primary: false
  weight: 100
  editorHidden: true

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  weight: -94
  primary: false
  editorHidden: true

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  weight: -93
  editorHidden: true

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - Detective
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Warden
  editorHidden: true

- type: department
  id: Epistemics
  description: department-Epistemics-description
  color: "#D381C9"
  weight: -92
  primary: false
  editorHidden: true

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: -91
  primary: false
  editorHidden: true

- type: department
  id: NCWL
  description: department-NCWL-description
  color: "#FFD580"
  weight: 100
  roles:
  - CommandantNCWL
  - KommissarNCWL
  - MVDGruntNCWL
  - FleetkapitanNCWL
  - PartisanNCWL
  - DirectorNCWL
  - DoctorNCWL
  - WorkerOverbossNCWL
  - DockhandNCWL
  - IndustryTaskmasterNCWL
  - ArtificerNCWL
  - WorkerNCWL
  editorHidden: false

- type: department
  id: NCSP
  description: department-NCSP-description
  color: "#DC143C"
  weight: 90
  roles:
  - RingleaderNCSP
  - LieutenantNCSP
  - InfanteerNCSP
  - TechnicianNCSP
  - CoordinatorNCSP
  - RipperdocNCSP
  - TraumasecNCSP
  - OperativeNCSP
  - IntelligenceOfficerNCSP
  - CyberdawnTechNCSP
  - ForemanNCSP
  - ShipbreakerNCSP
  editorHidden: false

- type: department
  id: DSM
  description: department-DSM-description
  color: "#684871"
  weight: 85
  roles:
  - FreeholderDSM
  - LevymanDSM
  - KnightDSM
  - RitterDSM
  - WealthDSM
  - ForemanDSM
  - ScribeDSM
  - TemplarDSM
  - SurgeonDSM
  - LaborDSM
  - CourtierDSM
  - AdjutantDSM
  - GovernorDSM
  - AdvocatusDSM
  - ArchmaesterDSM
  editorHidden: false

- type: department
  id: SRM
  description: department-SRM-description
  color: "#4a6741"
  weight: 80
  roles:
  - TenderSRM
  - AcolyteSRM
  - HunterSRM
  - MontagneSRM
  - OverseerSRM
  editorHidden: false # i just like to see them for the numbers , SPCR 2025

- type: department
  id: SHI
  description: department-SHI-description
  color: "#4a6741"
  weight: 75
  roles:
  - ExecutiveSHI
  - BoardSHI
  - HighsecSHI
  - CorpsecSHI
  - EmployeeSHI
  - MedtechSHI
  - BoardHRSHI
  - HosSHI
  editorHidden: false

- type: department
  id: CMM
  description: department-CMM-description
  color: "#5191e0"
  weight: 70
  roles:
  - OrdnancemanCMM
  - MachinistCMM
  - PhysicianCMM
  - MinutemanCMM
  - WatchmasterCMM
  - DeputyMarshalCMM
  - MarshalCMM
  editorHidden: true

- type: department
  id: TAP
  description: department-TAP-description
  color: "#50c878"
  weight: 55
  roles:
  # - ProphetTAP #commented the rest until TAP comes back .2 | 2025
  # - AcolyteTAP
  # - TinkererTAP
  # - TechminerTAP
  # - HangarTechTAP
  - Antiquarian
  - BeltrunnerTAP
  - DraugrTAP
  - ServileTAP
  editorHidden: false

- type: department
  id: ATH
  description: department-ATH-description
  color: "#ffffed"
  weight: 40
  roles:
  - KommandantATH
  - LeutnantATH
  - KanoneerATH
  - SoldatATH
  - SanitatATH
  - StewardATH
  - OberartzATH
  - LogistatATH
  - HandelsATH
  - ForscherATH
  - ChirurgeonATH
  - VorarbeiterATH
  - ArbeiterATH
  editorHidden: true # i just like to see them for the numbers , SPCR 2025

  # CONSCRIPT

- type: department
  id: NCWL-W
  description: department-NCWL-description
  color: "#FFD580"
  weight: 11
  roles:
  - ConscriptLeaderNCWL
  - ConscriptOfficerNCWL
  - ConscriptSniperNCWL
  - ConscriptGunnerNCWL
  - ConscriptDoctorNCWL
  - ConscriptShotgunNCWL
  - ConscriptSubmachinegunNCWL
  - ConscriptRiflemanNCWL
  - ConscriptCadetNCWL
  - ConscriptShipCaptainNCWL
  - ConscriptShipCrewNCWL
  editorHidden: true

- type: department
  id: DSM-W
  description: department-DSM-description
  color: "#684871"
  weight: 10
  roles:
  - ConscriptLeaderDSM
  - ConscriptOfficerDSM
  - ConscriptSniperDSM
  - ConscriptGunnerDSM
  - ConscriptDoctorDSM
  - ConscriptShotgunDSM
  - ConscriptSubmachinegunDSM
  - ConscriptRiflemanDSM
  - ConscriptCadetDSM
  - ConscriptShipCaptainDSM
  - ConscriptShipCrewDSM
  editorHidden: true
