- type: department
  id: Logistics
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  - MailCarrier

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - MartialArtist
  - Prisoner
  - Gladiator

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
  weight: 120

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - ChiefJustice
  - AdministrativeAssistant
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  primary: false
  weight: 100

- type: department
  id: Dignitary
  description: department-Dignitary-description
  color: "#33FE6D"
  roles:
  - BlueshieldOfficer
  - NanotrasenRepresentative
  - Magistrate
  primary: false
  weight: 101

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - SeniorEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - SeniorPhysician
  - MedicalBorg

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - SeniorOfficer
  - Detective
  - Warden
  - PrisonGuard
  - Brigmedic

- type: department
  id: Epistemics
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher
  - Scientist
  - ResearchAssistant
  - Chaplain
  - ForensicMantis
  - Librarian
  - Roboticist

- type: department
  id: Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  - Psychologist
  - MartialArtist
  - Gladiator
  - Prisoner
  - Brigmedic
  primary: false
