- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 7200 #DeltaV 2 hours
  startingGear: BoxerGear
  conditionalStartingGear:
    - id: BoxerPlasmamanGear
      requirements:
      - !type:CharacterSpeciesRequirement
        species: [ Plasmaman ]
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  access:
  - Maintenance
  - Theatre # DeltaV - Add Theatre access
  - Boxer # DeltaV - Add Boxer access
  special: # Nyanotrasen - BoxerComponent, see Content.Server/Nyanotrasen/Abilities/Boxer/Boxer/BoxerComponent.cs
  - !type:AddComponentSpecial
    components:
    - type: Boxer
      modifiers:
        coefficients: # These only apply to unarmed
          Blunt: 1.5
          Slash: 1.5
          Piercing: 1.5

- type: startingGear
  id: BoxerGear
  equipment:
    jumpsuit: UniformShortsRed
    back: ClothingBackpackFilled
    id: BoxerPDA
    ears: ClothingHeadsetService
    gloves: ClothingHandsGlovesBoxingRed
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
  innerClothingSkirt: UniformShortsRedWithTop
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled

- type: startingGear
  id: BoxerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuit
    head: ClothingHeadEnvirohelm
    # No envirogloves, use the boxing gloves
