- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
    - !type:CharacterEmployerRequirement
      employers:
      - OrionExpress
      - IdrisIncorporated
      - NanoTrasen
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Mail
  - Quartermaster
  - Maintenance
  - Command
  - Orders
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8

- type: startingGear
  id: QuartermasterGear
  subGear:
  - QuartermasterPlasmamanGear
  equipment:
    head: ClothingHeadHatBeretLogi
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackQuartermasterFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetAltCargo
    belt: BoxFolderClipboard
    pocket1: AppraisalTool

- type: startingGear
  id: QuartermasterPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitQM
    head: ClothingHeadEnvirohelmQM
    gloves: ClothingHandsGlovesEnviroglovesCargo
