- type: job
  id: ChiefJustice
  name: job-name-chief-justice
  description: job-description-chief-justice
  playTimeTracker: JobChiefJustice
  requirements:
    - !type:CharacterPlaytimeRequirement
      tracker: JobClerk
      min: 36000 # 10 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobLawyer
      min: 36000 # 10 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobProsecutor
      min: 36000 # 10 hours
    - !type:CharacterOverallTimeRequirement
      min: 90000 # 25 hours
    - !type:CharacterWhitelistRequirement # whitelist requirement because I don't want any dingus judges
  weight: 20
  startingGear: CJGear
  conditionalStartingGear:
    - id: LawyerPlasmamanGear
      requirements:
      - !type:CharacterSpeciesRequirement
        species: [ Plasmaman ]
  icon: "JobIconChiefJustice"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - ChiefJustice
  - Justice
  - Security
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CJGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChiefJustice
    back: ClothingBackpackFilled # TODO- make Justice department bags
    shoes: ClothingShoesLeather
    head: ClothingHeadHatCJToque
    outerClothing: ClothingOuterChiefJustice
    id: ChiefJusticePDA
    ears: ClothingHeadsetAltJustice
    gloves: ClothingHandsGlovesColorWhite
    # Todo - pocket1: Gavel
  innerClothingSkirt: ClothingUniformJumpskirtChiefJustice
  satchel: ClothingBackpackSatchelFilled # TODO- make Justice departmebt bags
  duffelbag: ClothingBackpackDuffelFilled


