- type: job
  id: Clerk
  name: job-name-clerk
  description: job-description-clerk
  playTimeTracker: JobClerk
  antagAdvantage: 2
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 36000 # 10 hrs
    - !type:CharacterPlaytimeRequirement
      tracker: JobLawyer
      min: 36000 # 10 hours
    - !type:CharacterPlaytimeRequirement
      tracker: JobProsecutor
      min: 36000 # 10 hours


  startingGear: ClerkGear
  icon: "JobIconClerk"
  requireAdminNotify: true
  supervisors: job-supervisors-cj
  canBeAntag: false
  access:
  - Justice
  - Security
  - Maintenance

- type: startingGear
  id: ClerkGear
  subGear:
  - PassengerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitClerk
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: ClerkPDA
    ears: ClothingHeadsetJustice
  innerClothingSkirt: ClothingUniformJumpskirtClerk
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled


