- type: job
  id: DirectorNCWL
  name: job-name-ncwl-medical-director
  description: job-description-ncwl-medical-director
  playTimeTracker: JobMedicalLeaderNCWL
  weight: 7
  startingGear: DirectorNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLMedicalLeader"
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-medi-leader
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - NCWLGeneral
  - NCWLKommissar
  - NCWLJail
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: DirectorNCWLGear
  equipment:
    shoes: ClothingShoesBootsJack
    jumpsuit: ClothingUniformJumpsuitNCWLMedic
    id: NCWLMedicalLeaderPDA
    outerClothing: ClothingOuterArmorNCWLCarapaceVrachev
    belt: ClothingBeltMedicalFilled
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesNitrile
    head: ClothingHeadHatNCWLBeretMedi
    eyes: ClothingEyesHudMedSec
    ears: ClothingHeadsetNCWL
