- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  antagAdvantage: 2 # DeltaV - Reduced TC: Security Radio and Access
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 36000 # 10 hrs
    - !type:CharacterDepartmentTimeRequirement # DeltaV - Security dept time requirement
      department: Security
      min: 14400 # 4 hours
  conditionalStartingGear:
    - id: LawyerPlasmamanGear
      requirements:
      - !type:CharacterSpeciesRequirement
        species: [ Plasmaman ]
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-cj  # Delta V - Change supervisor to chief justice
  access:
  - Service
  - Lawyer
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackLawyerFilled #DeltaV - stamp included
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    pocket1: BookSecurity
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelLawyerFilled #DeltaV - stamp included
  duffelbag: ClothingBackpackDuffelLawyerFilled #DeltaV - stamp included

- type: startingGear
  id: LawyerPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitEnviroslacks
    head: ClothingHeadEnvirohelmWhite
    gloves: ClothingHandsGlovesEnviroglovesWhite
