- type: job
  id: AdjutantDSM
  name: job-name-adjutant
  description: job-description-adjutant
  playTimeTracker: JobAdjutantDSM
  weight: 99
  startingGear: AdjutantGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconImperialAdjutant"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterOverallTimeRequirement
      min: 36000
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Pacifist
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-adjutant
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - HighImperial
          - LowImperial
          - Tradeband
        addUnderstood:
          - HighImperial
          - LowImperial
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - DSMFunds
  - Maintenance
  - EmpireNoble
  - EmpireAdjutant
  - EmpireSoldier
  - Service
  - Empire
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - DSMFunds
  - ScribesGuild
  - LogisticsWealth

- type: startingGear
  id: AdjutantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialAdjutantFormal
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsImperialLongboots
    head: ClothingHeadHatImperialBeret
    outerClothing: ClothingOuterCoatImperialAdjutant
    id: AdjutantPDA
    pocket2: WeaponRevolverSnubnose
    ears: ClothingHeadsetEmpire
    gloves: ClothingHandsGlovesImperialAdjutantGloves
