- type: job
  id: CourtierDSM
  name: job-name-courtier
  description: job-description-courtier
  playTimeTracker: JobCourtierDSM
  weight: 52
  startingGear: CourtierGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconImperialCourtier"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterOverallTimeRequirement
      min: 2500
    - !type:CharacterSpeciesRequirement
      species:
        - Human
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-courtier
      - type: LanguageAdder
        addSpoken:
          - HighImperial
          - LowImperial
          - Tradeband
        addUnderstood:
          - HighImperial
          - LowImperial
          - Tradeband
  access:
  - Command
  - Empire
  - EmpireNoble
  - Maintenance
  - Service
  - EmpireSoldier
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: CourtierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialNobleMale
    shoes: ClothingShoesBootsImperialLaceup
    id: CourtierPDA
    ears: ClothingHeadsetEmpireCiv
