- type: job
  id: CourtierDSM
  name: job-name-courtier
  description: job-description-courtier
  playTimeTracker: JobCourtierDSM
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 2500
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Shadowkin
    - !type:FactionRequirement
      factionID: "DSM"
  weight: 78
  startingGear: CourtierGear
  alwaysUseSpawner: true
  icon: "JobIconImperialCourtier"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-courtier
      - type: LanguageKnowledge
        speaks:
          - HighImperial
          - SolCommon
        understands:
          - HighImperial
          - Tradeband
          - SolCommon
  access:
  - Command
  - Empire
  - EmpireNoble
  - Maintenance
  - Service
  - EmpireSoldier
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: CourtierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialNobleMale
    shoes: ClothingShoesBootsImperialLaceup
    id: CourtierPDA
    ears: ClothingHeadsetEmpire
