- type: job
  id: ForemanDSM
  name: job-name-foremanimp
  description: job-description-foremanimp
  playTimeTracker: JobForemanDSM
  weight: 19
  startingGear: ForemanImpGear
  alwaysUseSpawner: true
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  icon: "JobIconImperialForeman"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial
  canBeAntag: false
  access:
  - Command
  - Empire
  - Maintenance
  - Service
  - ScribesGuild
  - LogisticsWealth
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ForemanImpGear
  equipment:
    id: ForemanImpPDA
    ears: ClothingHeadsetEmpireCiv
    head: ClothingHeadHelmetImperialWorkerHelmet
    mask: ClothingMaskImperialCombatGasmask
    shoes: ClothingShoesBootsImperialLongboots
    jumpsuit: ClothingUniformJumpsuitImperialFreeholder
    gloves: ClothingHandsGlovesImperialWorkerGloves

