- type: job
  id: ForemanDSM
  name: job-name-foremanimp
  description: job-description-foremanimp
  playTimeTracker: JobForemanDSM
  weight: 3
  startingGear: ForemanImpGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconImperialForeman"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-foreman
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - LowImperial
          - Tradeband
        addUnderstood:
          - LowImperial
          - Tradeband
  access:
  - Command
  - Empire
  - Maintenance
  - Service
  - ScribesGuild
  - LogisticsWealth
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ForemanImpGear
  equipment:
    id: ForemanImpPDA
    ears: ClothingHeadsetEmpireCiv
    head: ClothingHeadHelmetImperialWorkerHelmet
    mask: ClothingMaskImperialCombatGasmask
    shoes: ClothingShoesBootsImperialLongboots
    jumpsuit: ClothingUniformJumpsuitImperialFreeholder
    gloves: ClothingHandsGlovesImperialWorkerGloves
