- type: job
  id: FreeholderDSM
  name: job-name-freeholder
  description: job-description-freeholder
  playTimeTracker: JobFreeholderDSM
  weight: 1
  startingGear: FreeholderGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconImperialFreeholder"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-freeholder
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - LowImperial
        addUnderstood:
          - LowImperial
  access:
  - Command
  - Maintenance
  - Empire
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: FreeholderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialFreeholder
    id: FreeholderPDA
    belt: ClothingBeltSalvageWebbingFilledNF
    ears: ClothingHeadsetEmpireCiv
    shoes: ClothingShoesBootsImperialLongboots
    back: ClothingBackpackDSM
