- type: job
  id: GovernorDSM
  name: job-name-governor
  description: job-description-governor
  playTimeTracker: JobGovernorDSM
  weight: 100
  startingGear: GovernorGear
  alwaysUseSpawner: true
  requireAdminNotify: true
  icon: "JobIconImperialGovernor"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:SexRequirement
      sex : Male
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Pacifist
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-baron
      - type: LanguageKnowledge
        speaks:
          - HighImperial
          - LowImperial
          - TauCetiBasic
          - Tradeband
          - Sign
        understands:
          - HighImperial
          - LowImperial
          - TauCetiBasic
          - Tradeband
          - Sign
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - LogisticsWealth
  - ScribesGuild
  - Archmaester
  - Maintenance
  - Advocatus
  - EmpireNoble
  - EmpireAdjutant
  - DSMFunds
  - EmpireGovernor
  - EmpireSoldier
  - Service
  - Empire
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: GovernorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialGovernor
    shoes: ClothingShoesBootsImperialGovernorBoots
    back: ClothingBackpackSatchelLeatherFilledDSM
    head: ClothingHeadHatImperialBicorne
    outerClothing: ClothingOuterCoatImperialGovernor
    id: GovernorPDA
    ears: ClothingHeadsetEmpire
