- type: job
  id: KnightDSM
  name: job-name-knight
  description: job-description-knight
  playTimeTracker: JobKnightDSM
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 35000
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Shadowkin
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Pacifist
        - WheelchairBound
  weight: 81
  startingGear: KnightGear
  alwaysUseSpawner: true
  icon: "JobIconImperialKnight"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-knight
      - type: LanguageKnowledge
        speaks:
          - HighImperial
          - Tradeband
          - SolCommon
        understands:
          - HighImperial
          - Tradeband
          - SolCommon

  access:
  - Command
  - Empire
  - Maintenance
  - Service
  - ScribesGuild
  - LogisticsWealth
  - EmpireNoble
  - EmpireSoldier
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: KnightGear
  equipment:
    id: KnightPDA
    ears: ClothingHeadsetEmpire
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    shoes: ClothingShoesBootsImperialJackboots
    head: ClothingHeadHelmetImperialKnightCommanderHelmet
    outerClothing: ClothingOuterArmorImperialArmorPrestige
    gloves: ClothingHandsGlovesImperialLonggloves
    pocket1: ImperialPassportBareLegit
