- type: job
  id: KnightDSM
  name: job-name-knight
  description: job-description-knight
  playTimeTracker: JobKnightDSM
  weight: 50
  startingGear: KnightGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconImperialKnight"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterOverallTimeRequirement
      min: 35000
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-knight
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - HighImperial
          - LowImperial
        addUnderstood:
          - HighImperial
          - LowImperial
  access:
  - Command
  - Empire
  - Maintenance
  - Service
  - ScribesGuild
  - LogisticsWealth
  - EmpireNoble
  - EmpireSoldier
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: KnightGear
  equipment:
    id: KnightPDA
    ears: ClothingHeadsetEmpire
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    shoes: ClothingShoesBootsImperialJackboots
    back: ClothingBackpackDSM
    head: ClothingHeadHelmetImperialKnightCommanderHelmet
    outerClothing: ClothingOuterArmorImperialArmorPrestige
    gloves: ClothingHandsGlovesImperialLonggloves
    pocket1: WeaponPistolNeoVolker
    pocket2: RomaineBible
    belt: ClothingBeltAssault
  storage:
    belt:
      - Flash
      - Tourniquet
      - MagazineMagnum
      - CombatKnife
      - Zipties
