- type: job
  id: LevymanDSM
  name: job-name-levyman
  description: job-description-levyman
  playTimeTracker: JobLevymanDSM
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Shadowkin
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 77
  startingGear: LevymanGear
  alwaysUseSpawner: true
  icon: "JobIconImperialLevyman"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-manatarms
  access:
  - Command
  - Empire
  - Maintenance
  - Service
  - EmpireSoldier
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: LevymanGear
  equipment:
    id: LevymanPDA
    ears: ClothingHeadsetEmpire
    shoes: ClothingShoesBootsImperialJackboots
    head: ClothingHeadHelmetImperialTrooperHelmet
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    outerClothing: ClothingOuterArmorImperialTrooperArmor
    gloves: ClothingHandsGlovesImperialLonggloves

- components:
  - type: LanguageKnowledge
    speaks:
      - SolCommon
    understands:
      - Tradeband
      - SolCommon
