- type: job
  id: LevymanDSM
  name: job-name-levyman
  description: job-description-levyman
  playTimeTracker: JobLevymanDSM
  weight: 4
  startingGear: LevymanGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconImperialLevyman"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
        - Oni
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-manatarms
      - type: LanguageAdder
        addSpoken:
          - LowImperial
        addUnderstood:
          - LowImperial
  access:
  - Command
  - Empire
  - Maintenance
  - Service
  - EmpireSoldier
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: LevymanGear
  equipment:
    id: LevymanPDA
    ears: ClothingHeadsetEmpireCiv
    shoes: ClothingShoesBootsImperialJackboots
    back: ClothingBackpackDSMFilledSoldier
    head: ClothingHeadHelmetImperialTrooperHelmet
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    outerClothing: ClothingOuterArmorImperialTrooperArmor
    gloves: ClothingHandsGlovesImperialLonggloves
