- type: job
  id: LaborDSM
  name: job-name-ministerlabor
  description: job-description-labor
  playTimeTracker: JobLaborDSM
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 2500
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Shadowkin
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
  weight: 84
  startingGear: LaborGear
  alwaysUseSpawner: true
  icon: "JobIconImperialLabor"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ministry
  access:
  - Command
  - Empire
  - EmpireNoble
  - Maintenance
  - Service
  - EmpireSoldier
  - LogisticsWealth
  - ScribesGuild
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: LaborGear
  equipment:
    head: ClothingHeadHatImperialPeakedCap
    jumpsuit: ClothingUniformJumpsuitImperialNobleMale
    shoes: ClothingShoesBootsImperialLaceup
    outerClothing: ClothingOuterCoatImperialParade
    id: CourtierPDA
    ears: ClothingHeadsetEmpire
