- type: job
  id: RitterDSM
  name: job-name-ritter
  description: job-description-ritter
  playTimeTracker: JobRitterDSM
  weight: 51
  startingGear: RitterGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconImperialRitter"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterOverallTimeRequirement
      min: 30000
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
      - Muted
      - Pacifist
      - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-knight
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - HighImperial
          - LowImperial
        addUnderstood:
          - HighImperial
          - LowImperial

  access:
  - Command
  - Empire
  - Maintenance
  - Service
  - ScribesGuild
  - LogisticsWealth
  - EmpireNoble
  - EmpireSoldier
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: RitterGear
  equipment:
    id: RitterPDA
    ears: ClothingHeadsetEmpire
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    shoes: ClothingShoesBootsImperialJackboots
    outerClothing: ClothingOuterCoatImperialRitter
    gloves: ClothingHandsGlovesImperialLonggloves
