- type: job
  id: ScribeDSM
  name: job-name-imperialresearch
  description: job-description-scribe
  playTimeTracker: JobScribeDSM
  weight: 93
  startingGear: ScribeGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconImperialScribe"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-smarts
      - type: HullrotFaction
        faction: DSM
      - type: BibleUser
      - type: LanguageAdder
        addSpoken:
          - LowImperial
        addUnderstood:
          - LowImperial
  access:
  - Command
  - Empire
  - Maintenance
  - ScribesGuild
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ScribeGear
  equipment:
    id: ScribePDA
    ears: ClothingHeadsetEmpireCiv
    pocket2: RomaineBible
    mask: ClothingMaskImperialAdjutantMask
    shoes: ClothingShoesBootsImperialClogs
    jumpsuit: ClothingUniformJumpsuitImperialDoctor
