- type: job
  id: SurgeonDSM
  name: job-name-surgeon
  description: job-description-surgeon
  playTimeTracker: JobSurgeonDSM
  weight: 2
  startingGear: SurgeonGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconImperialSurgeon"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-smarts
      - type: HullrotFaction
        faction: DSM
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 1.75
      - type: LanguageAdder
        addSpoken:
          - LowImperial
        addUnderstood:
          - LowImperial
  access:
  - Command
  - Empire
  - Maintenance
  - ScribesGuild
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: SurgeonGear
  equipment:
    id: SurgeonPDA
    ears: ClothingHeadsetEmpireCiv
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatImperialSurgeon
    back: ClothingBackpackDSM
    gloves: ClothingHandsGlovesNitrile
    belt: ClothingBeltMedicalFilled
    shoes: ClothingShoesBootsImperialLaceup
    jumpsuit: ClothingUniformJumpsuitImperialSurgeon
