- type: job
  id: TemplarDSM
  name: job-name-advocatustemplar
  description: job-description-advocatustemplar
  playTimeTracker: JobTemplarDSM
  weight: 97
  startingGear: TemplarGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconAdvocatusTemplar"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterOverallTimeRequirement
      min: 55000
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:SexRequirement
      sex: Male
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-templar
      - type: BibleUser
      - type: LanguageAdder
        addSpoken:
          - HighImperial
          - LowImperial
        addUnderstood:
          - HighImperial
          - LowImperial
  access:
  - Command
  - Empire
  - Advocatus
  - Maintenance
  - Service
  - ScribesGuild
  - LogisticsWealth
  - EmpireNoble
  - EmpireSoldier
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: TemplarGear
  equipment:
    id: TemplarPDA
    ears: ClothingHeadsetEmpire
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    back: ClothingBackpackDSMFilledSoldier
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesImperialLonggloves
    pocket2: RomaineBible
