- type: job
  id: WealthDSM
  name: job-name-wealth
  description: job-description-wealth
  playTimeTracker: JobWealthDSM
  weight: 95
  startingGear: WealthGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconImperialWealth"
  supervisors: job-supervisors-imperial
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterOverallTimeRequirement
      min: 10800
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ministry
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - HighImperial
          - LowImperial
          - Tradeband
        addUnderstood:
          - HighImperial
          - LowImperial
          - Tradeband
  access:
  - Command
  - Empire
  - EmpireNoble
  - Maintenance
  - LogisticsWealth
  - Service
  - EmpireSoldier
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: WealthGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialNobleMale
    back: ClothingBackpackSatchelLeather
    shoes: ClothingShoesBootsImperialLongboots
    head: ClothingHeadHatImperialHeadwrap
    outerClothing: ClothingOuterCoatImperialMerchant
    gloves: ClothingHandsGlovesImperialGovernorGloves
    id: WealthPDA
    ears: ClothingHeadsetEmpire
    pocket2: SpaceCash10000
