- type: job
  id: APRTMontagneSRM
  name: job-name-montagne
  description: job-description-montagne
  playTimeTracker: JobMontagneSRM
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterOverallTimeRequirement
      min: 40000
    - !type:FactionRequirement
      factionID: "SRM"
  weight: 22
  startingGear: APRTMontagneGear
  alwaysUseSpawner: true
  icon: "JobIconMontagne"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial
  canBeAntag: false
  access:
  - Command
  - Hunter
  - HunterSenior
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddComponentSpecial
    components:
      - type: HullrotFaction
        faction: SRM
      - type: Telepathic
      - type: BibleUser

- type: startingGear
  id: APRTMontagneGear
  equipment:
    id: MontagnePDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunter
    shoes: ClothingShoesBootsMagCombat
    outerClothing: ClothingOuterHardsuitHunterElite
    suitstorage: JetpackBlueFilled
    gloves: ClothingHandsGlovesHunter
    pocket1: HandHeldMassScannerEE
    pocket2: ExtendedEmergencyOxygenTankFilled
    belt: ClothingBeltSheathKhopeshFilled
