- type: job
  id: PrisonGuard
  name: job-name-guard
  description: job-description-guard
  playTimeTracker: JobPrisonGuard
  startingGear: PrisonGuardGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconPrisonGuard"
  supervisors: job-supervisors-warden
  setPreference: true
#  whitelistRequired: true
  access:
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 6
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: PrisonGuardGear
  subGear:
  - PrisonGuardPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisonGuard
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadPrisonGuard
    id: PrisonGuardPDA
    ears: ClothingHeadsetPrisonGuard #DeltaV
    belt: ClothingBeltSecurityFilled
  innerClothingSkirt: ClothingUniformJumpsuitPrisonGuard
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled

- type: startingGear
  id: PrisonGuardPlasmamanGear
  parent: BasePlasmamanSecurityGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitPrisonGuard
    head: ClothingHeadEnvirohelmPrisonGuard
    gloves: ClothingHandsGlovesEnviroglovesBlack
