- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 24000
  - !type:CharacterDepartmentTimeRequirement
    department: Epistemics
    min: 38800
  - !type:CharacterPlaytimeRequirement
    tracker: JobJusticar
    min: 36000 # 10 hours
  - !type:CharacterPlaytimeRequirement
    tracker: JobScientist
    min: 36000 # 10 hours
  - !type:CharacterPlaytimeRequirement
    tracker: JobForensicMantis
    min: 36000 # 10 hours
  - !type:CharacterItemGroupRequirement
    group: TraitsCasterType
  - !type:CharacterLogicOrRequirement
    requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
      - IPC
    - !type:CharacterTraitRequirement
      traits:
      - AnomalousPositronics
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
    - Muted
    - Foreigner
    - ForeignerLight
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Mantis
  - Justicar
  - Chapel
  - External
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser
    - type: Psionic
      powerSlots: 3
      baselinePowerCost: 75
      nextPowerCost: 75
    - type: CommandStaff
    - type: InnatePsionicPowers
      powersToAdd:
      - DispelPower
      - MetapsionicPower
      - TelepathyPower
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  afterLoadoutSpecial:
  - !type:ModifyEnvirosuitSpecial
    charges: 8
  - !type:ModifyEnvirohelmSpecial
    powerCell: PowerCellHigh

- type: startingGear
  id: ResearchDirectorGear
  subGear:
  - ResearchDirectorPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackScience
    shoes: ClothingShoesColorBrown
    id: RnDPDA
    ears: ClothingHeadsetAltScience
    pocket1: BookPsionicsGuidebook
    pocket2: BibleMystagogue
  storage:
    back:
    - Flash

- type: startingGear
  id: ResearchDirectorPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitResearchDirector
    head: ClothingHeadEnvirohelmResearchDirector
    gloves: ClothingHandsGlovesEnviroglovesResearchDirector
