- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  antagAdvantage: 6
  requirements:
    - !type:DepartmentTimeRequirement
      department: Epistemics
      time: 54000
    - !type:OverallPlaytimeRequirement
      time: 72000
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Mantis
  - Chapel
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser
    - type: PotentialPsionic
    - type: Psionic
      dampening: 1 #Mystagogue gets a significant buff to his antimage abilities, making him better at dispelling than other people
    - type: DispelPower
    - type: CommandStaff
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    id: RnDPDA
    ears: ClothingHeadsetRD
    belt: BibleMystagogue
  innerClothingSkirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled
