- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Epistemics
    min: 14400 # 4 hours - same as scientist
  startingGear: RoboticistGear
  icon: "JobIconRoboticist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: RoboticistGear
  subGear:
  - RoboticistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitRoboticist
    back: ClothingBackpackRoboticsFilled
    shoes: ClothingShoesColorBlack
    outerClothing: ClothingOuterCoatRobo
    id: RoboticsPDA
    ears: ClothingHeadsetRobotics
    pocket1: BookPsionicsGuidebook
  innerClothingSkirt: ClothingUniformJumpskirtRoboticist
  satchel: ClothingBackpackSatchelRoboticsFilled
  duffelbag: ClothingBackpackDuffelRoboticsFilled

- type: startingGear
  id: RoboticistPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitRoboticist
    head: ClothingHeadEnvirohelmRoboticist
    gloves: ClothingHandsGlovesEnviroglovesRoboticist
