- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  guides: [ NuclearOperatives ]
- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  guides: [ NuclearOperatives ]

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  subGear:
  - SyndicatePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio60TC
    belt: ClothingBeltMilitaryWebbing
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative
