- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-head-objective
  requirements:
  - !type:CharacterOverallTimeRequirement # DeltaV - Playtime requirement
    min: 172800 # DeltaV - 48 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Command dept time requirement
    department: Command
    min: 36000 # DeltaV - 10 hours

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
