- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
    - id: FlashlightSeclite
    - id: WeaponDisabler
    - id: ClothingBeltSecurityFilled
    - id: ClothingHandsGlovesKravMaga
    - id: Flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHandsGlovesCombat
    - id: ClothingShoesBootsJack
    - id: ClothingOuterCoatWarden
    - id: ClothingOuterWinterWarden
    - id: RubberStampWarden
    - id: DoorRemoteArmory
    - id: ClothingOuterHardsuitCombatWarden
    - id: HoloprojectorSecurity
    - id: BookSpaceLaw
    - id: ClothingBackpackElectropack
      amount: 2
    - id: RemoteSignaller
      amount: 2
    - id: BoxPDAPrisoner
    - id: ClothingShoesBootsWinterWarden
    - id: BoxEncryptionKeyPrisoner
    - id: BoxPrisonerHeadset
    - id: LunchboxSecurityFilledRandom
      prob: 0.3

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
    - id: FlashlightSeclite
    - id: WeaponDisabler
    - id: ClothingBeltSecurityFilled
    - id: ClothingHandsGlovesKravMaga
    - id: Flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHandsGlovesCombat
    - id: ClothingShoesBootsJack
    - id: ClothingOuterCoatWarden
    - id: ClothingOuterWinterWarden
    - id: RubberStampWarden
    - id: DoorRemoteArmory
    - id: HoloprojectorSecurity
    - id: BookSpaceLaw
    - id: ClothingBackpackElectropack
      amount: 2
    - id: RemoteSignaller
      amount: 2
    - id: BoxPDAPrisoner
    - id: ClothingShoesBootsWinterWarden
    - id: BoxEncryptionKeyPrisoner
    - id: BoxPrisonerHeadset
    - id: LunchboxSecurityFilledRandom
      prob: 0.3

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
    - id: FlashlightSeclite
      prob: 0.8
    - id: WeaponDisabler
    - id: ClothingUniformJumpsuitSecGrey
      prob: 0.3
    - id: ClothingUniformJumpsuitSecBlue
      prob: 0.3
    - id: ClothingUniformJumpsuitSec
      prob: 0.3
    - id: ClothingUniformJumpskirtSecGrey
      prob: 0.3
    - id: ClothingUniformJumpskirtSecBlue
      prob: 0.3
    - id: ClothingUniformJumpskirtSec
      prob: 0.3
    - id: ClothingHeadHelmetBasic
    - id: ClothingHeadHelmetInsulated
      prob: 0.4
    - id: ClothingOuterArmorPlateCarrier
    - id: ClothingOuterArmorDuraVest
    - id: ClothingOuterStasecSweater
      prob: 0.75
    - id: ClothingUniformJumpsuitSecFormal
      prob: 0.25
    - id: ClothingBeltSecurityFilled
    - id: ClothingBeltCorporateJudo
    - id: Flash
      prob: 0.5
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHandsGlovesColorBlack
    - id: ClothingShoesBootsJack
    - id: WeaponMeleeNeedle
      prob: 0.1
    - id: HoloprojectorSecurity
      prob: 0.6
    - id: BookSpaceLaw
      prob: 0.5
    - id: LunchboxSecurityFilledRandom
      prob: 0.3

- type: entity
  id: LockerBrigmedicFilled
  suffix: Corpsman, Filled
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesGlassesCorpsman
    - id: WeaponDisabler
    - id: TrackingImplanter
      amount: 2
    - id: BoxSterileMask
    - id: ClothingHeadHatBeretCorpsman
    - id: ClothingUniformJumpsuitBrigmedic
    - id: ClothingUniformJumpskirtBrigmedic
    - id: HandheldGPSBasic
    - id: MedkitFilled
    - id: MedkitCombatFilled
      prob: 0.6
    - id: MedkitAdvancedFilled
      prob: 0.4
    - id: MedkitOxygenFilled
      prob: 0.3
    - id: MedkitBruteFilled
      prob: 0.3
    - id: MedkitToxinFilled
      prob: 0.3
    - id: MedkitBurnFilled
      prob: 0.7
    - id: LunchboxSecurityFilledRandom
      prob: 0.3

- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Corpsman, Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesGlassesCorpsman
    - id: WeaponDisabler
    - id: TrackingImplanter
      amount: 2
    - id: ClothingOuterHardsuitCombatCorpsman
    - id: ClothingUniformJumpsuitBrigmedic
    - id: ClothingUniformJumpskirtBrigmedic
    - id: HandheldGPSBasic
    - id: MedkitFilled
    - id: MedkitCombatFilled
      prob: 0.6
    - id: MedkitAdvancedFilled
      prob: 0.4
    - id: MedkitOxygenFilled
      prob: 0.3
    - id: MedkitBruteFilled
      prob: 0.3
    - id: MedkitToxinFilled
      prob: 0.3
    - id: MedkitBurnFilled
      prob: 0.7
    - id: LunchboxSecurityFilledRandom
      prob: 0.3

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesGlassesSecurity
      prob: 0.3
    - id: ClothingHeadHatFedoraBrown
    - id: ClothingNeckTieDet
    - id: ClothingOuterVestDetective
    - id: ClothingOuterCoatDetective
    - id: FlashlightSeclite
    - id: ForensicScanner
    - id: LogProbeCartridge
    - id: BoxForensicPad
    - id: DrinkDetFlask
    - id: ClothingHandsGlovesForensic
    - id: RubberStampDetective
    - id: HoloprojectorSecurity
    - id: BoxEvidenceMarkers
    - id: BoxTapeRecorder
    - id: LunchboxSecurityFilledRandom
      prob: 0.3
    - id: HandLabeler

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
    - id: ClothingHeadHelmetBombSuit
    - id: ClothingOuterSuitBomb
    # NT is cheap, what can you do...
    - id: Wirecutter
      prob: 0.9
    - id: Screwdriver
      prob: 0.9
    - id: Multitool
      prob: 0.5

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  name: wt550 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponLaserCarbine
      amount: 3

- type: entity
  id: GunSafeRifleBRDIR25
  suffix: BRDI-R25
  parent: GunSafe
  name: BRDI-R25 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunBRDIR25
      amount: 2
    - id: MagazineCaselessRifle
      amount: 4
