- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      min: 21600 # 6 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      min: 18000 # 4 hrs
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - Shadowkin
  startingGear: CorpsmanGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  - External
  - Corpsman
  extendedAccess:
  - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CPRTraining

- type: startingGear
  id: CorpsmanGear # see Prototypes/Roles/Jobs/Fun/misc_startinggear.yml for "BrigmedicGear"
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    outerClothing: ClothingOuterArmorPlateCarrier
    back: ClothingBackpackBrigmedicFilled
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretCorpsman
    id: CorpsmanPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltCorpsmanWebbingFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerClothingSkirt: ClothingUniformJumpskirtBrigmedic
  satchel: ClothingBackpackSatchelBrigmedicFilled
  duffelbag: ClothingBackpackDuffelBrigmedicFilled
