- type: job
  id: AdministratorNCWL
  name: job-name-administrator
  description: job-description-administrator
  playTimeTracker: JobAdministratorNCWL
  weight: 60
  startingGear: AdministratorGear
  alwaysUseSpawner: true
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  requirements:
    - !type:WhitelistRequirement
    - !type:FactionRequirement
      factionID: "NCWL"
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-admin
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - NCWLAdministrator
  - NCWLFunds
  - NCWLKommissar
  - NCWLGeneral
  - NCWLArmory
  - NCWLCommand
  - NCWLJail
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: AdministratorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWLCommunications
    id: AdministratorPDA
    neck: ClothingNeckAdminCapelet
    ears: ClothingHeadsetNCWL
    belt: ClothingBeltNCWLWebbing
    pocket1: NCWLPassportAccepted
    pocket2: WeaponPistolT91
