- type: job
  id: PartisanNCWL
  name: job-name-ncwl-partisan
  description: job-description-ncwl-partisan
  playTimeTracker: JobHomeguardSoldatNCWL
  weight: 5
  startingGear: SoldatNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLHomeguardSoldat"
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-ncwl-partisan
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-home-soldat
      - type: LanguageKnowledge
        speaks:
        - Dockta
        understands:
          - Dockta
          - Tradeband
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - NCWLArmory
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: SoldatNCWLGear
  equipment:
    shoes: ClothingShoesBootsJack
    jumpsuit: ClothingUniformJumpsuitNCWL
    id: NCWLHomeguardSoldatPDA
    outerClothing: ClothingOuterArmorNCWLHeavyCarapace
    belt: ClothingBeltNCWLPouches
    pocket1: WeaponPistolHKUSP
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesCombat
    head: ClothingHeadHelmetNCWLBasic
    mask: ClothingMaskNCWLGasmask
    ears: ClothingHeadsetNCWL
