- type: job
  id: DirectorNCWL
  name: job-name-ncwl-medical-director
  description: job-description-ncwl-medical-director
  playTimeTracker: JobMedicalLeaderNCWL
  weight: 96
  startingGear: DirectorNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLMedicalLeader"
  requirements:
  - !type:CharacterSpeciesRequirement
    inverted: true
    species:
      - Voidborn
  - !type:CharacterOverallTimeRequirement
    min: 20000
  - !type:FactionRequirement
    factionID: "NCWL"
  - !type:CharacterTraitRequirement
    inverted: true
    traits:
      - Muted
      - Blindness
      - Pacifist
      - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-ncwl-leaders
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-medi-leader
      - type: HullrotFaction
        faction: NCWL
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 2.5
      - type: LanguageAdder
        addSpoken:
          - Dockta
          - Tradeband
        addUnderstood:
          - Dockta
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - NCWLGeneral
  - NCWLJail
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: DirectorNCWLGear
  equipment:
    shoes: ClothingShoesBootsCombat
    jumpsuit: ClothingUniformJumpsuitNCWLMedic
    id: NCWLMedicalLeaderPDA
    outerClothing: ClothingOuterArmorNCWLCarapaceVrachev
    belt: ClothingBeltMedicalFilled
    pocket1: WeaponPistolComrade
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesNitrile
    head: ClothingHeadHatNCWLBeretMedi
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetNCWL
