- type: job
  id: EngineerNCWL
  name: job-name-ncwl-engineering-mechanic
  description: job-description-ncwl-engineering-mechanic
  playTimeTracker: JobEngineeringWorkerNCWL
  weight: 4
  startingGear: EngineerNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLEngineeringWorker"
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Shadowkin
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-ncwl-sindikat
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-engi-worker
      - type: LanguageKnowledge
        speaks:
          - Dockta
        understands:
          - Dockta
          - Tradeband
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: EngineerNCWLGear
  equipment:
    shoes: ClothingShoesBootsSalvage
    jumpsuit: ClothingUniformJumpsuitNCWLArtificer
    id: NCWLEngineeringWorkerPDA
    belt: ClothingBeltUtilityFilled
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesColorYellow
    ears: ClothingHeadsetNCWL
