- type: job
  id: PartisanNCWL
  name: job-name-ncwl-partisan
  description: job-description-ncwl-partisan
  playTimeTracker: JobHomeguardSoldatNCWL
  weight: 97
  startingGear: SoldatNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconNCWLHomeguardSoldat"
  supervisors: job-supervisors-ncwl-partisan
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterOverallTimeRequirement
      min: 1000
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-home-soldat
      - type: HullrotFaction
        faction: NCWL
      - type: LanguageAdder
        addSpoken:
          - Dockta
        addUnderstood:
          - Dockta
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - NCWLArmory
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: SoldatNCWLGear
  equipment:
    shoes: ClothingShoesBootsCombat
    jumpsuit: ClothingUniformJumpsuitNCWL
    id: NCWLHomeguardSoldatPDA
    outerClothing: ClothingOuterArmorNCWLHeavyCarapace
    pocket1: WeaponPistolComrade
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesCombat
    head: ClothingHeadHelmetNCWLBasic
    mask: ClothingMaskNCWLGasmask
    ears: ClothingHeadsetNCWL
    belt: ClothingBeltNCWLPouches
  storage:
    belt:
      - Flash
      - Tourniquet
      - MagazinePistol
      - CombatKnife
      - Zipties
