- type: job
  id: FleetkapitanNCWL
  name: job-name-ncwl-fleetkapitan
  description: job-description-ncwl-fleetkapitan
  playTimeTracker: JobHomeguardSquadCaptainNCWL
  weight: 98
  startingGear: CaptainNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconNCWLHomeguardSquadCaptain"
  supervisors: job-supervisors-ncwl-leaders
  canBeAntag: false
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-home-squad-lead
      - type: HullrotFaction
        faction: NCWL
      - type: LanguageAdder
        addSpoken:
          - Dockta
        addUnderstood:
          - Dockta
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - NCWLGeneral
  - NCWLJail
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: CaptainNCWLGear
  equipment:
    shoes: ClothingShoesBootsCombat
    jumpsuit: ClothingUniformJumpsuitNCWL
    id: NCWLHomeguardSquadCaptainPDA
    outerClothing: ClothingOuterArmorNCWLCarapaceKapitan
    belt: ClothingBeltNCWLPouches
    pocket1: WeaponPistolT91
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesCombat
    head: ClothingHeadHatNCWLBeret
    mask: ClothingMaskNCWLGasmask
    ears: ClothingHeadsetNCWL
    eyes: ClothingEyesHudSecurity
  storage:
    back:
      - Flash
      - Tourniquet
      - Zipties
      - CombatKnife
