- type: job
  id: MVDGruntNCWL
  name: job-name-ncwl-mvd-grunt
  description: job-description-ncwl-mvd-grunt
  playTimeTracker: JobMVDGruntNCWL
  weight: 99
  startingGear: MVDGruntNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconUnionfallNCWLRifleman"
  supervisors: job-supervisors-ncwl-mvd
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterSpeciesRequirement
      species:
        - Human
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-mvd-grunt
      - type: HullrotFaction
        faction: NCWL
      - type: LanguageAdder
        addSpoken:
          - Dockta
        addUnderstood:
          - Dockta
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - NCWLGeneral
  - NCWLJail
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: MVDGruntNCWLGear
  equipment:
    shoes: ClothingShoesBootsMVD
    jumpsuit: ClothingUniformJumpsuitMVD
    id: NCWLMVDGruntPDA
    outerClothing: ClothingOuterArmorMVDJacket
    pocket1: WeaponPistolComrade
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesMVD
    ears: ClothingHeadsetNCWL
    suitstorage: WeaponSubMachineGunMilitant
