- type: job
  id: DockhandNCWL
  name: job-name-ncwl-logistic-dockhand
  description: job-description-ncwl-logistic-dockhand
  playTimeTracker: JobLogisticWorkerNCWL
  weight: 2
  startingGear: DockhandNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLLogisticWorker"
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - Blindness
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-ncwl-koalitsiya
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-logi-worker
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: DockhandNCWLGear
  equipment:
    shoes: ClothingShoesBootsSalvage
    jumpsuit: ClothingUniformJumpsuitNCWLTelnikSleeved
    id: NCWLLogisticWorkerPDA
    belt: ClothingBeltSalvageWebbing
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesFingerless
    head: ClothingHeadHatNCWLTanker
    ears: ClothingHeadsetNCWL

- type: LanguageKnowledge
  speaks:
    - Dockta
    - Tradeband
  understands:
    - Dockta
    - Tradeband
