- type: job
  id: SoldatNCWL
  name: job-name-ncwl-homeguard-soldat
  description: job-description-ncwl-homeguard-soldat
  playTimeTracker: JobHomeguardSoldatNCWL
  weight: 8
  startingGear: SoldatNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLHomeguardSoldat"
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 1000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-ncwl-homeguard
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-home-soldat
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: SoldatNCWLGear
  equipment:
    shoes: ClothingShoesBootsJack
    jumpsuit: ClothingUniformJumpsuitNCWL
    id: NCWLHomeguardSoldatPDA
    outerClothing: ClothingOuterArmorNCWLHeavyCarapace
    belt: ClothingBeltNCWLPouches
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesCombat
    head: ClothingHeadHelmetNCWLBasic
    ears: ClothingHeadsetNCWL
