- type: job
  id: WorkerNCWL
  name: job-name-ncwl-newbie
  description: job-description-ncwl-newbie
  playTimeTracker: JobWorkerNCWL
  weight: 1
  startingGear: WorkerNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLWorker"
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - Blindness
  requireAdminNotify: false
  supervisors: job-supervisors-ncwl-worker
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-worker
      - type: LanguageKnowledge
        speaks:
          - Dockta
          - Tradeband
        understands:
          - Dockta
          - Tradeband
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: WorkerNCWLGear
  equipment:
    shoes: ClothingShoesBootsSalvage
    jumpsuit: ClothingUniformJumpsuitNCWLTrainee
    id: NCWLWorkerPDA
    belt: ClothingBeltUtilityFilled
    back: ClothingBackpackNCWL
    ears: ClothingHeadsetNCWL
