- type: job
  id: ArtificerNCWL
  name: job-name-ncwl-artificer
  description: job-description-ncwl-artificer
  playTimeTracker: JobLogisticLeaderNCWL
  weight: 2
  startingGear: DockmasterNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconNCWLArtificer"
  supervisors: job-supervisors-ncwl-leaders
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 1000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-logi-leader
      - type: HullrotFaction
        faction: NCWL
      - type: LanguageAdder
        addSpoken:
          - Dockta
        addUnderstood:
          - Dockta
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - NCWLGeneral
  - NCWLJail
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: DockmasterNCWLGear
  equipment:
    shoes: ClothingShoesBootsSalvage
    jumpsuit: ClothingUniformJumpsuitNCWLArtificer
    id: NCWLLogisticLeaderPDA
    belt: ClothingBeltUtilityEngineering
    pocket1: WeaponPistolComrade
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesColorYellow
    head: ClothingHeadHatNCWLCapsoft
    eyes: ClothingEyesGlassesMeson
    ears: ClothingHeadsetNCWL
