- type: job
  id: DoctorNCWL
  name: job-name-ncwl-medical-doctor
  description: job-description-ncwl-medical-doctor
  playTimeTracker: JobMedicalWorkerNCWL
  weight: 3
  startingGear: DoctorNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconNCWLSanitar"
  supervisors: job-supervisors-ncwl-partisan
  canBeAntag: false
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 1000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-medi-worker
      - type: HullrotFaction
        faction: NCWL
      - type: CPRTraining
      - type: SurgerySpeedModifier
        speedModifier: 1.75
      - type: LanguageAdder
        addSpoken:
          - Dockta
        addUnderstood:
          - Dockta
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: DoctorNCWLGear
  equipment:
    shoes: ClothingShoesBootsCombat
    jumpsuit: ClothingUniformJumpsuitNCWLMedic
    id: NCWLMedicalWorkerPDA
    outerClothing: ClothingOuterArmorNCWLMedi
    belt: ClothingBeltMedicalFilled
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesNitrile
    head: ClothingHeadHatNCWLCapsoftMedical
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetNCWL
