- type: job
  id: CommandantNCWL
  name: job-name-ncwl-faction-leader
  description: job-description-ncwl-faction-leader
  playTimeTracker: JobFactionLeaderNCWL
  weight: 102
  startingGear: CommandantNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconNCWLFactionLeader"
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterOverallTimeRequirement
      min: 35000
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterWhitelistRequirement
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-faction-leader
      - type: HullrotFaction
        faction: NCWL
      - type: LanguageAdder
        addSpoken:
          - Dockta
          - Tradeband
        addUnderstood:
          - Dockta
          - Tradeband
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - NCWLGeneral
  - NCWLKommissar
  - NCWLJail
  - NCWLArmory
  - NCWLCommand
  - NCWLAdministrator

- type: startingGear
  id: CommandantNCWLGear
  equipment:
    shoes: ClothingShoesBootsNCWLAdmiralParade
    jumpsuit: ClothingUniformJumpsuitNCWLCommunications
    id: NCWLFactionLeaderPDA
    outerClothing: ClothingOuterArmorNCWLOpremeCarapace
    belt: ClothingBeltNCWLDoubleHolster
    pocket1: WeaponRevolverPython
    pocket2: WeaponRevolverPython
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesNCWLAdmiralParade
    head: ClothingHeadHatNCWLBeretAdmiral
    mask: ClothingMaskNCWLGasmask
    ears: ClothingHeadsetNCWL
    eyes: ClothingEyesHudSecurity
