- type: job
  id: WorkerNCWL
  name: job-name-ncwl-newbie
  description: job-description-ncwl-newbie
  playTimeTracker: JobWorkerNCWL
  weight: 1
  startingGear: WorkerNCWLGear
  alwaysUseSpawner: true
  requireAdminNotify: false
  icon: "JobIconNCWLWorker"
  supervisors: job-supervisors-ncwl-worker
  canBeAntag: false
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-worker
      - type: HullrotFaction
        faction: NCWL
      - type: LanguageAdder
        addSpoken:
          - Dockta
        addUnderstood:
          - Dockta
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: WorkerNCWLGear
  equipment:
    shoes: ClothingShoesBootsSalvage
    jumpsuit: ClothingUniformJumpsuitNCWLTrainee
    id: NCWLWorkerPDA
    belt: ClothingBeltSalvageWebbingFilledNF
    back: ClothingBackpackNCWL
    ears: ClothingHeadsetNCWL
