- type: job
  id: DoctorNCWL
  name: job-name-ncwl-medical-doctor
  description: job-description-ncwl-medical-doctor
  playTimeTracker: JobMedicalWorkerNCWL
  weight: 4
  startingGear: DoctorNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconNCWLMedicalWorker"
  requirements:
    - !type:CharacterSpeciesRequirement
      inverted: true
      species:
        - Voidborn
    - !type:CharacterOverallTimeRequirement
      min: 1000
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-ncwl-partisan
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-medi-worker
      - type: LanguageKnowledge
        speaks:
          - Dockta
          - Tradeband
        understands:
          - Dockta
          - Tradeband
  access:
  - Command
  - Maintenance
  - Service
  - NCWLJail #needed for balreska morgue
  - NCWLGeneral
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: DoctorNCWLGear
  equipment:
    shoes: ClothingShoesBootsJack
    jumpsuit: ClothingUniformJumpsuitNCWLMedic
    id: NCWLMedicalWorkerPDA
    outerClothing: ClothingOuterArmorNCWLMedi
    belt: ClothingBeltMedicalFilled
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesNitrile
    head: ClothingHeadHatNCWLCapsoftMedical
    eyes: ClothingEyesHudMedical
    ears: ClothingHeadsetNCWL
