- type: job
  id: ConscriptCadetNCWL
  name: job-name-conscript-ncwl-cadet
  description: job-description-conscript-ncwl-cadet
  playTimeTracker: ConscriptJobCadetNCWL
  weight: 10
  startingGear: ConscriptCadetNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconKadet"
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-highcomm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-soldat
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ConscriptCadetNCWLGear
  equipment:
    head: ClothingHeadHatNCWLCapsoft
    mask: ClothingMaskPilot
    jumpsuit: ClothingUniformJumpsuitNCWL
    outerClothing: ClothingOuterArmorNCWLHeavyCarapace
    shoes: ClothingShoesBootsJack
    belt: ClothingBeltNCWLPouchesFilledRifleman
    back: WeaponSniperNCWLNovomosin
    pocket1: EmergencyOxygenTankFilled
    pocket2: GrenadeShrapnel
    ears: ClothingHeadsetNCWL
    id: KadetPDA
    suitstorage: WeaponPistolComrade
