- type: job
  id: ConscriptSubmachinegunNCWL
  name: job-name-conscript-ncwl-smg
  description: job-description-conscript-ncwl-smg #change me later
  playTimeTracker: ConscriptJobSubmachinegunNCWL
  weight: 10
  startingGear: ConscriptSubmachinegunNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconSanitar"
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-conscript-ncwl
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-cqc
      - type: HullrotFaction
        faction: NCWL
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NCWLAdministrator
  - NCWLFunds
  - NCWLKommissar
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: ConscriptSubmachinegunNCWLGear
  equipment:
    head: ClothingHeadHelmetNCWLBasic
    neck: ClothingNeckIFFOrange
    mask: ClothingMaskPilot
    jumpsuit: ClothingUniformJumpsuitNCWL
    outerClothing: ClothingOuterArmorNCWLHeavyCarapace
    shoes: ClothingShoesBootsMagCombat
    belt: ClothingBeltNCWLPouchesFilledSubmachinegun
    back: ClothingBackpackNCWL
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: GrenadeFlashBang
    ears: ClothingHeadsetNCWL
    eyes: ClothingEyesGlassesNCWL
    id: SanitarPDA
    suitstorage: WeaponSubMachineGunNCWLPartisan
    gloves: ClothingHandsGlovesCombat
  inhand:
    - WeaponPistolComrade
