- type: job
  id: ConscriptShipCrewNCWL
  name: job-name-conscript-ncwl-ship-crew
  description: job-description-conscript-ncwl-ship-crew
  playTimeTracker: ConscriptJobShipCrewNCWL
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 10
  startingGear: ConscriptShipCrewNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconUnionfallNCWLCrew"
  requireAdminNotify: true
  supervisors: job-supervisors-conscript-ncwl
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-crew
      - type: HullrotFaction
        faction: NCWL
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - NCWLGeneral
  - Service
  - NCWLKommissar
  - NCWLJail
  - NCWLArmory
  - NCWLCommand
  - External
  - Captain # Frontier

- type: startingGear
  id: ConscriptShipCrewNCWLGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWLArtificer
    neck: ClothingNeckIFFOrange
    id: SanitarPDA
    ears: ClothingHeadsetNCWL
    shoes: ClothingShoesBootsMagNCWL
    head: ClothingHeadHatNCWLBeret
    belt: ClothingBeltAssaultFilledCrew #drips better
    pocket1: DoubleEmergencyOxygenTankFilled
    back: ClothingBackpackNCWL
    gloves: ClothingHandsGlovesCombat
  inhand:
    - BookUnionfallNCWLGuide
  storage:
    back:
      - VoidsuitKitNCWL
      - BoxMRE
      - WeaponPistolT91
