- type: job
  id: ConscriptCadetNCWL
  name: job-name-conscript-ncwl-cadet
  description: job-description-conscript-ncwl-cadet
  playTimeTracker: ConscriptNCWL
  weight: 1
  startingGear: ConscriptCadetNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconUnionfallNCWLCadet"
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-conscript-ncwl
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-new
      - type: HullrotFaction
        faction: NCWL
  access:
  - Command
  - Maintenance
  - Service
  - NCWLGeneral
  - NCWLJail
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NCWLAdministrator
  - NCWLFunds
  - NCWLKommissar
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: ConscriptCadetNCWLGear
  equipment:
    head: ClothingHeadHatNCWLCapsoft
    neck: ClothingNeckIFFOrange
    mask: ClothingMaskPilot
    jumpsuit: ClothingUniformJumpsuitNCWL
    outerClothing: ClothingOuterArmorNCWLHeavyCarapace
    shoes: ClothingShoesBootsMagNCWL
    belt: ClothingBeltNCWLPouchesFilledRifleman
    back: ClothingBackpackNCWL
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: GrenadeFlashBang
    ears: ClothingHeadsetNCWL
    id: NCWLHomeguardSoldatPDA
    suitstorage: WeaponSniperNCWLNovomosin
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesNCWL
  inhand:
    - BookUnionfallNCWLGuide
  storage:
    back:
      - VoidsuitKitNCWL
      - BoxMRE
      - BoxFlare
      - WeaponPistolComrade
