- type: job
  id: ForensicMantis
  name: job-name-mantis
  description: job-description-mantis
  playTimeTracker: JobForensicMantis
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 18000
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      min: 3600
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - IPC
        - !type:CharacterTraitRequirement
          traits:
            - AnomalousPositronics
  startingGear: ForensicMantisGear
  icon: "JobIconForensicMantis"
  supervisors: job-supervisors-rd
  antagAdvantage: 5 # DeltaV - From 4 to 5
  canBeAntag: true # DeltaV - Mantis is no longer a Detective
  # whitelistRequired: true
  access:
  - Research
  - Maintenance
  - Mantis # DeltaV - Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  special:
  - !type:AddComponentSpecial
    components:
    - type: Psionic
      powerSlots: 2
  - !type:AddComponentSpecial
    components:
    - type: InnatePsionicPowers
      powersToAdd:
        - MetapsionicPower
        - TelepathyPower
        - AssayPower

- type: startingGear
  id: ForensicMantisGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMantis
    back: ClothingBackpackMantisFilled
    shoes: ClothingShoesBootsMantis
    head: ClothingHeadHatFezMantis
    id: ForensicMantisPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetScience # DeltaV - Mantis is part of Epistemics
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCoatMantis
    belt: ClothingBeltMantis
    pocket1: BookPsionicsGuidebook
  innerClothingSkirt: ClothingUniformSkirtMantis
  satchel: ClothingBackpackSatchelMantisFilled
  duffelbag: ClothingBackpackDuffelMantisFilled
