- type: entity
  parent: BlueshieldAmmunitionBox
  id: BlueshieldAmmunitionBoxFilled
  suffix: Filled
  components:
  - type: StorageFill
    contents:
    - id: MagazineBoxMagnum
    - id: MagazineBoxMagnumFlash
    - id: MagazineBoxMagnumEMP
    - id: MagazineMagnumLeverRifleEmpty
      amount: 2
