# - type: cargoProduct
#   id: ServiceJanitorialHayes
#   icon:
#     sprite: Objects/Specific/Janitorial/janitorial.rsi
#     state: cleaner
#   product: CrateServiceJanitorialSupplies
#   cost: 560
#   category: cargoproduct-category-name-service
#   group: hayes

# - type: cargoProduct
#   id: ServiceLightsReplacementHayes
#   icon:
#     sprite: Objects/Power/light_bulb.rsi
#     state: normal
#   product: CrateServiceReplacementLights
#   cost: 600
#   category: cargoproduct-category-name-service
#   group: hayes

# - type: cargoProduct
#   id: MousetrapBoxesHayes
#   icon:
#     sprite: Objects/Devices/mousetrap.rsi
#     state: mousetrap
#   product: CrateMousetrapBoxes
#   cost: 500
#   category: cargoproduct-category-name-service
#   group: hayes

# - type: cargoProduct
#   id: ServiceBureaucracyHayes
#   icon:
#     sprite: Objects/Misc/bureaucracy.rsi
#     state: pen
#   product: CrateServiceBureaucracy
#   cost: 1000
#   category: cargoproduct-category-name-service
#   group: hayes

# - type: cargoProduct
#   id: ServiceBooksHayes
#   icon:
#     sprite: Objects/Misc/books.rsi
#     state: book_icon
#   product: CrateServiceBooks
#   cost: 1000
#   category: cargoproduct-category-name-service
#   group: hayes

