- type: job
  id: UnionfallOfficerNCWL
  name: job-name-unionfall-ncwl-officer
  description: job-description-unionfall-ncwl-officer
  playTimeTracker: ConscriptNCWL
  requirements:
    - !type:FactionRequirement
      factionID: "NCWL"
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 8
  startingGear: UnionfallOfficerNCWLGear
  alwaysUseSpawner: true
  icon: "JobIconUnionfallNCWLOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-unionfall-ncwl-high
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-ncwl-officer
      - type: HullrotFaction
        faction: NCWL
      - type: LanguageAdder
        addSpoken:
          - Dockta
        addUnderstood:
          - Dockta
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - NCWLGeneral
  - NCWLKommissar
  - NCWLJail
  - NCWLArmory
  - NCWLCommand

- type: startingGear
  id: UnionfallOfficerNCWLGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNCWLKommissar
    neck: ClothingNeckIFFOrange
    id: NCWLHomeguardSquadCaptainPDA
    ears: ClothingHeadsetNCWL
    shoes: ClothingShoesBootsMagNCWL
    outerClothing: ClothingOuterArmorNCWLCarapace
    head: ClothingHeadHatNCWLKommissarHat
    belt: ClothingBeltNCWLPouchesFilledKommissar
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: SyndicateWhistle
    back: ClothingBackpackNCWL
    suitstorage: WeaponSniperNCWLNovomosin
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesNCWL
  inhand:
    - ClothingOuterHardsuitNCWLInfantry
    - JetpackBlackFilled
  storage:
    back:
      - BoxMRE
      - WeaponPistolT91
      - CrowbarRed
      - HandHeldMassScannerEE
