- type: job
  id: UnionfallShipCrewDSM
  name: job-name-conscript-dsm-ship-crew
  description: job-description-conscript-dsm-ship-crew
  playTimeTracker: ConscriptDSM
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 10
  startingGear: UnionfallShipCrewDSMGear
  alwaysUseSpawner: true
  icon: "JobIconUnionfallDSMCrew"
  requireAdminNotify: true
  supervisors: job-supervisors-conscript-dsm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-dsm-crew
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - LowImperial
        addUnderstood:
          - LowImperial
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Service
  - Empire

- type: startingGear
  id: UnionfallShipCrewDSMGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialFreeholder
    neck: ClothingNeckIFFCyan
    back: ClothingBackpackDSM
    shoes: ClothingShoesBootsMagDSM
    head: ClothingHeadHelmetImperialWorkerHelmet
    gloves: ClothingHandsGlovesImperialWorkerGloves
    id: LevymanPDA
    belt: ClothingBeltAssaultFilledCrew
    pocket1: DoubleEmergencyOxygenTankFilled
    ears: ClothingHeadsetEmpire
    eyes: ClothingEyesHudSecurity
    outerClothing: ClothingOuterHardsuitImperialWorker
  inhand:
    - BookUnionfallDSMGuide
  storage:
    back:
      - BoxMRE
      - WeaponPistolNeoVolker
