- type: job
  id: UnionfallCadetDSM
  name: job-name-unionfall-dsm-cadet
  description: job-description-unionfall-dsm-cadet #change me later
  playTimeTracker: ConscriptDSM
  weight: 2
  startingGear: UnionfallCadetDSMGear
  alwaysUseSpawner: true
  icon: "JobIconUnionfallDSMCadet"
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-unionfall-dsm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-dsm-new
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - LowImperial
        addUnderstood:
          - LowImperial
  access:
  - Command
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - Empire

- type: startingGear
  id: UnionfallCadetDSMGear
  equipment:
    neck: ClothingNeckIFFCyan
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    outerClothing: ClothingOuterHardsuitImperialSoldier
    shoes: ClothingShoesBootsMagDSM
    belt: ClothingBeltAssaultFilledRifleman
    gloves: ClothingHandsGlovesImperialLonggloves
    back: ClothingBackpackDSM
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ExGrenade
    ears: ClothingHeadsetEmpire
    id: LevymanPDA
    suitstorage: WeaponSniperDSMLegax
    eyes: ClothingEyesHudSecurity
  inhand:
    - BookUnionfallDSMGuide
    - JetpackBlackFilled
  storage:
    back:
      - BoxMRE
      - WeaponPistolComplianceImperial
      - CrowbarRed
      - HandHeldMassScannerEE
