- type: job
  id: UnionfallShipCaptainDSM
  name: job-name-unionfall-dsm-ship-captain
  description: job-description-unionfall-dsm-ship-captain
  playTimeTracker: ConscriptDSM
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 11
  startingGear: UnionfallShipCaptainDSMGear
  alwaysUseSpawner: true
  icon: "JobIconUnionfallDSMCaptain"
  requireAdminNotify: true
  supervisors: job-supervisors-unionfall-dsm-high
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-dsm-captain
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - LowImperial
          - HighImperial
        addUnderstood:
          - LowImperial
          - HighImperial
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Service
  - Empire

- type: startingGear
  id: UnionfallShipCaptainDSMGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMilitaryCaptain
    neck: ClothingNeckIFFCyan
    back: ClothingBackpackDSM
    shoes: ClothingShoesBootsMagDSM
    head: ClothingHeadHatImperialPeakedCap
    outerClothing: ClothingOuterCoatImperialParade
    id: KnightPDA
    belt: ClothingBeltAssaultFilledCrew
    pocket1: DoubleEmergencyOxygenTankFilled
    ears: ClothingHeadsetEmpire
    eyes: ClothingEyesHudSecurity
  storage:
    back:
      - VoidsuitKitDSM
      - BoxMRE
      - WeaponPistolNeoVolker
