- type: job
  id: UnionfallDoctorDSM
  name: job-name-unionfall-dsm-doctor
  description: job-description-unionfall-dsm-doctor
  playTimeTracker: ConscriptDSM
  weight: 7
  startingGear: UnionfallDoctorDSMGear
  alwaysUseSpawner: true
  icon: "JobIconUnionfallDSMMedic"
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterOverallTimeRequirement
      min: 1000
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Blindness
        - Pacifist
        - WheelchairBound
  requireAdminNotify: false
  supervisors: job-supervisors-unionfall-dsm
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-dsm-doctor
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - LowImperial
        addUnderstood:
          - LowImperial
  access:
  - Command
  - Maintenance
  - ScribesGuild
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - Empire

- type: startingGear
  id: UnionfallDoctorDSMGear
  equipment:
    head: ClothingHeadHatImperialSurgeon
    neck: ClothingNeckIFFCyan
    jumpsuit: ClothingUniformJumpsuitImperialSurgeon
    outerClothing: ClothingOuterHardsuitImperialWorker
    shoes: ClothingShoesBootsMagDSM
    belt: ClothingBeltAssaultFilledMedic
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesNitrile
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: ParamedHypo
    ears: ClothingHeadsetEmpire
    id: SurgeonPDA
    suitstorage: WeaponPistolNeoVolker
    back: ClothingBackpackSatchelMedical
  inhand:
    - BookUnionfallDSMGuide
    - JetpackBlackFilled
  storage:
    back:
      - DefibrillatorCompact
      - BoxMRE
      - MedkitCombatFilled
      - OmnizineChemistryBottle
      - Bloodpack
      - CartridgePuncturase
      - CartridgePuncturase
      - CartridgePuncturase
      - CartridgePuncturase
      - CartridgePuncturase
      - CrowbarRed
      - HandHeldMassScannerEE
