- type: job
  id: UnionfallOfficerDSM
  name: job-name-unionfall-dsm-officer
  description: job-description-unionfall-dsm-officer
  playTimeTracker: ConscriptDSM
  requirements:
    - !type:FactionRequirement
      factionID: "DSM"
    - !type:CharacterOverallTimeRequirement
      min: 20000
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Muted
        - Blindness
        - Pacifist
        - WheelchairBound
  weight: 8
  startingGear: UnionfallOfficerDSMGear
  alwaysUseSpawner: true
  icon: "JobIconUnionfallDSMOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-unionfall-dsm-high
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-dsm-officer
      - type: HullrotFaction
        faction: DSM
      - type: LanguageAdder
        addSpoken:
          - LowImperial
          - HighImperial
        addUnderstood:
          - LowImperial
          - HighImperial
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Mercenary # Frontier
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Service
  - Empire

- type: startingGear
  id: UnionfallOfficerDSMGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialGovernor
    neck: ClothingNeckIFFCyan
    back: ClothingBackpackDSM
    shoes: ClothingShoesBootsMagDSM
    head: ClothingHeadHatImperialBeret
    outerClothing: ClothingOuterHardsuitImperialCommand
    id: KnightPDA
    belt: ClothingBeltAssaultFilledAdjutant
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: SyndicateWhistle
    ears: ClothingHeadsetEmpire
    suitstorage: WeaponSniperDSMLegax
    eyes: ClothingEyesHudSecurity
  inhand:
    - JetpackBlackFilled
  storage:
    back:
      - BoxMRE
      - WeaponPistolNeoVolker
      - CrowbarRed
      - HandHeldMassScannerEE
